// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for motorbikes - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_motorbikes
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_AAF_B_M1030",
			"OFCRA_CC4_O_UK3CB_AAF_O_M1030"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_motorbikes",
			"UK3CB_Factions_AAF_B",
			"UK3CB_Factions_AAF_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_B_M1030_AAF;
	class UK3CB_O_M1030_AAF;
	class UK3CB_AAF_B_M1030: UK3CB_B_M1030_AAF
	{
		class EventHandlers;
	};
	class UK3CB_AAF_O_M1030: UK3CB_O_M1030_AAF
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_M1030: UK3CB_AAF_B_M1030
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\motorbikes\motorbikes_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_motorbikes\data\m1030_alfa_ca.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_AAF_O_M1030: UK3CB_AAF_O_M1030
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\motorbikes\motorbikes_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_motorbikes\data\m1030_alfa_ca.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
