// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 9: UK3CB_Quadbike (OFCRA_CC4) - spawnable: UK3CB_AAF_B_Quadbike, UK3CB_AAF_I_Quadbike, UK3CB_AAF_O_Quadbike, UK3CB_ADA_B_Quadbike, UK3CB_ADA_I_Quadbike, UK3CB_ADA_O_Quadbike, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_quadbike
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Quadbike"
		};
	};
};

class CfgVehicles
{
	class UK3CB_Quadbike_Base;

	class UK3CB_Quadbike: UK3CB_Quadbike_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\quadbike\quadbike_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_quadbike\data\ion_quadbike_01_wheel_co.paa"
				};
				factions[] = {};
			};
		};
	};
};
