// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// ugv01_stomper is split by required addons (2 configs) so a missing mod only skips its own part
// vehicles.txt line 42: UGV_01_base_F (OFCRA_CC4) - spawnable: B_T_UGV_01_olive_F, B_T_UGV_01_rcws_olive_F, B_UGV_01_F, B_UGV_01_rcws_F, C_IDAP_UGV_01_F, I_E_UGV_01_F, ...
// vehicles.txt line 42: UGV_01_base_F (OFCRA_CC4_db) - spawnable: B_T_UGV_01_olive_F, B_T_UGV_01_rcws_olive_F, B_UGV_01_F, B_UGV_01_rcws_F, C_IDAP_UGV_01_F, I_E_UGV_01_F, ...
// vehicles.txt line 42: UGV_01_base_F (OFCRA_CC4_olive) - spawnable: B_T_UGV_01_olive_F, B_T_UGV_01_rcws_olive_F, B_UGV_01_F, B_UGV_01_rcws_F, C_IDAP_UGV_01_F, I_E_UGV_01_F, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_db", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_olive", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_ugv01_stomper
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"A3_Drones_F_Soft_F_Gamma_UGV_01"
		};
	};
};

class CfgVehicles
{
	class Car_F;

	class UGV_01_base_F: Car_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_db
			{
				displayName = "OFCRA CC4 Dark Brown";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_db.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_db.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_db.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_olive
			{
				displayName = "OFCRA CC4 Olive";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_olive.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_olive.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_olive.paa"
				};
				factions[] = {};
			};
		};
	};
};
