// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for m60 - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_m60
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_AAF_B_M60A3",
			"OFCRA_CC4_O_UK3CB_KRG_O_M60A1"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_m60",
			"UK3CB_Factions_AAF_B",
			"UK3CB_Factions_KRG_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_B_M60A3_AAF;
	class UK3CB_O_M60A1_DES;
	class UK3CB_AAF_B_M60A3: UK3CB_B_M60A3_AAF
	{
		class EventHandlers;
	};
	class UK3CB_KRG_O_M60A1: UK3CB_O_M60A1_DES
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_M60A3: UK3CB_AAF_B_M60A3
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\m60\m60_0.paa",
			"ofcra_cc4\m60\m60_1.paa",
			"ofcra_cc4\m60\m60_2.paa",
			"ofcra_cc4\m60\m60_3.paa",
			"ofcra_cc4\m60\m60_4.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_KRG_O_M60A1: UK3CB_KRG_O_M60A1
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\m60\m60_0.paa",
			"ofcra_cc4\m60\m60_1.paa",
			"ofcra_cc4\m60\m60_2.paa",
			"ofcra_cc4\m60\m60_3.paa",
			"ofcra_cc4\m60\m60_4.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
