// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for orca - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_orca
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_ION_B_Urban_Orca_Armed_AT",
			"OFCRA_CC4_O_UK3CB_CSAT_A_O_Orca_Armed_AT",
			"OFCRA_CC4_B_UK3CB_ION_B_Urban_Orca",
			"OFCRA_CC4_O_UK3CB_CSAT_A_O_Orca"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_orca",
			"UK3CB_Factions_ION_B_Urban",
			"UK3CB_Factions_CSAT_A_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_O_Orca_CSAT_A;
	class UK3CB_O_Orca_Armed_AT_CSAT_A;
	class UK3CB_B_Orca_ION;
	class UK3CB_B_Orca_Armed_AT_ION;
	class UK3CB_CSAT_A_O_Orca: UK3CB_O_Orca_CSAT_A
	{
		class EventHandlers;
	};
	class UK3CB_CSAT_A_O_Orca_Armed_AT: UK3CB_O_Orca_Armed_AT_CSAT_A
	{
		class EventHandlers;
	};
	class UK3CB_ION_B_Urban_Orca: UK3CB_B_Orca_ION
	{
		class EventHandlers;
	};
	class UK3CB_ION_B_Urban_Orca_Armed_AT: UK3CB_B_Orca_Armed_AT_ION
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_ION_B_Urban_Orca_Armed_AT: UK3CB_ION_B_Urban_Orca_Armed_AT
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Helipilot_F";
		typicalCargo[] = {"B_Helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\orca\orca_0.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_CSAT_A_O_Orca_Armed_AT: UK3CB_CSAT_A_O_Orca_Armed_AT
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_helipilot_F";
		typicalCargo[] = {"O_helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\orca\orca_0.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_B_UK3CB_ION_B_Urban_Orca: UK3CB_ION_B_Urban_Orca
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Helipilot_F";
		typicalCargo[] = {"B_Helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\orca\orca_0.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_CSAT_A_O_Orca: UK3CB_CSAT_A_O_Orca
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_helipilot_F";
		typicalCargo[] = {"O_helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\orca\orca_0.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
