// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 13: rhsusf_mrzr_base (OFCRA_CC4) - spawnable: rhsusf_mrzr4_d
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_mrzr
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"rhsusf_c_mrzr"
		};
	};
};

class CfgVehicles
{
	class MRAP_01_base_F;

	class rhsusf_mrzr_base: MRAP_01_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\mrzr\mrzr_0.paa",
					"ofcra_cc4\mrzr\mrzr_1.paa",
					"ofcra_cc4\mrzr\mrzr_2.paa",
					"ofcra_cc4\mrzr\mrzr_3.paa",
					"ofcra_cc4\mrzr\mrzr_4.paa",
					"",
					"",
					"",
					"",
					"",
					"",
					""
				};
				factions[] = {};
			};
		};
	};
};
