// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 32: rhsusf_MATV_base (OFCRA_CC4) - spawnable: rhsusf_m1240a1_m240_uik_usarmy_d, rhsusf_m1240a1_m240_uik_usarmy_wd, rhsusf_m1240a1_m240_usarmy_d, rhsusf_m1240a1_m240_usarmy_wd, rhsusf_m1240a1_m240_usmc_d, rhsusf_m1240a1_m240_usmc_wd, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_matv
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"rhsusf_c_MATV"
		};
	};
};

class CfgVehicles
{
	class MRAP_01_base_F;

	class rhsusf_MATV_base: MRAP_01_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\matv\matv_0.paa",
					"ofcra_cc4\matv\matv_1.paa",
					"ofcra_cc4\matv\matv_2.paa",
					"\rhsusf\addons\rhsusf_matv\data\rhsusf_matv_decal_ca.paa",
					"ofcra_cc4\matv\matv_4.paa",
					"ofcra_cc4\matv\matv_5.paa",
					"ofcra_cc4\matv\matv_6.paa",
					"ofcra_cc4\matv\matv_7.paa",
					"ofcra_cc4\matv\matv_8.paa",
					"\rhsusf\addons\rhsusf_matv\data\rhsusf_matva1qnet_wd_ca.paa",
					"ofcra_cc4\matv\matv_10.paa",
					"\a3\map_vr\data\picturemap_ca.paa"
				};
				factions[] = {};
			};
		};
	};
};
