// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 30: BWA3_Tiger_base (OFCRA_CC4) - spawnable: BWA3_Tiger, BWA3_Tiger_RMK
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_tiger
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"bwa3_tiger"
		};
	};
};

class CfgVehicles
{
	class Helicopter_Base_F;

	class BWA3_Tiger_base: Helicopter_Base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\tiger\tiger_0.paa",
					"ofcra_cc4\tiger\tiger_1.paa",
					"ofcra_cc4\tiger\tiger_2.paa",
					"ofcra_cc4\tiger\tiger_3.paa",
					"\bwa3_tiger\data\symbols\3_ca.paa",
					"\bwa3_tiger\data\symbols\0_ca.paa",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"#(argb,8,8,3)color(0,0,0,0,co)",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					"",
					""
				};
				factions[] = {};
			};
		};
	};
};
