// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 46: UAV_02_base_F (OFCRA_CC4) - spawnable: B_UAV_02_dynamicLoadout_F, B_UAV_02_LM_G, I_UAV_02_dynamicLoadout_F, I_UAV_02_LM_G, O_UAV_02_dynamicLoadout_F, O_UAV_02_LM_G
// vehicles.txt line 46: UAV_02_base_F (OFCRA_CC4_db) - spawnable: B_UAV_02_dynamicLoadout_F, B_UAV_02_LM_G, I_UAV_02_dynamicLoadout_F, I_UAV_02_LM_G, O_UAV_02_dynamicLoadout_F, O_UAV_02_LM_G
// vehicles.txt line 46: UAV_02_base_F (OFCRA_CC4_olive) - spawnable: B_UAV_02_dynamicLoadout_F, B_UAV_02_LM_G, I_UAV_02_dynamicLoadout_F, I_UAV_02_LM_G, O_UAV_02_dynamicLoadout_F, O_UAV_02_LM_G
// vehicles.txt line 46: B_UAV_02_LM_G (OFCRA_CC4) - spawnable: B_UAV_02_LM_G, I_UAV_02_LM_G, O_UAV_02_LM_G
// vehicles.txt line 46: B_UAV_02_LM_G (OFCRA_CC4_db) - spawnable: B_UAV_02_LM_G, I_UAV_02_LM_G, O_UAV_02_LM_G
// vehicles.txt line 46: B_UAV_02_LM_G (OFCRA_CC4_olive) - spawnable: B_UAV_02_LM_G, I_UAV_02_LM_G, O_UAV_02_LM_G
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_db", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_olive", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_uav02_greyhawk
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"A3_Drones_F_Air_F_Gamma_UAV_02",
			"Air_Globe_UAV_02"
		};
	};
};

class CfgVehicles
{
	class UAV;

	class UAV_02_base_F: UAV
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_db
			{
				displayName = "OFCRA CC4 Dark Brown";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_db.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_olive
			{
				displayName = "OFCRA CC4 Olive";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_olive.paa"
				};
				factions[] = {};
			};
		};
	};

	class B_UAV_02_LM_G: UAV_02_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_db
			{
				displayName = "OFCRA CC4 Dark Brown";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_db.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_olive
			{
				displayName = "OFCRA CC4 Olive";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_olive.paa"
				};
				factions[] = {};
			};
		};
	};
};
