// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for uav03_falcon - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_uav03_falcon
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_B_T_UAV_03_dynamicLoadout_F",
			"OFCRA_CC4_O_B_T_UAV_03_dynamicLoadout_F"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_uav03_falcon",
			"A3_Air_F_Exp_UAV_03"
		};
	};
};

class CfgVehicles
{
	class UAV_03_dynamicLoadout_base_F;
	class B_T_UAV_03_dynamicLoadout_F: UAV_03_dynamicLoadout_base_F
	{
		class EventHandlers;
		class Components;
		class ViewOptics;
		class Turrets;
	};
	class OFCRA_CC4_ti2_B_T_UAV_03_dynamicLoadout_F: B_T_UAV_03_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret;
		};
	};
	class OFCRA_CC4_ti3_B_T_UAV_03_dynamicLoadout_F: OFCRA_CC4_ti2_B_T_UAV_03_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn;
			};
		};
	};
	class OFCRA_CC4_ti4_B_T_UAV_03_dynamicLoadout_F: OFCRA_CC4_ti3_B_T_UAV_03_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide;
					class Medium;
					class Narrow;
				};
			};
		};
	};

	class OFCRA_CC4_B_B_T_UAV_03_dynamicLoadout_F: OFCRA_CC4_ti4_B_T_UAV_03_dynamicLoadout_F
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_UAV_AI";
		typicalCargo[] = {"B_UAV_AI"};
		displayName = "MQ-12 Falcon (no pylons)";
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav03_falcon\uav03_falcon_0.paa",
			"ofcra_cc4\uav03_falcon\uav03_falcon_1.paa",
			"ofcra_cc4\uav03_falcon\uav03_falcon_2.paa"
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				UIPicture = "\A3\Air_F_Exp\UAV_03\Data\UI\Map_UAV_03_3DEN_CA.paa";
				class Pylons
				{
					class Pylons1
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 5;
						UIposition[] = {0.0500000007450581, 0.300000011920929};
						turret[] = {0};
					};
					class Pylons2
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 4;
						UIposition[] = {0.100000001490116, 0.379999995231628};
						turret[] = {0};
					};
					class Pylons3
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 4;
						UIposition[] = {0.529999971389771, 0.379999995231628};
						turret[] = {0};
						mirroredMissilePos = 2;
					};
					class Pylons4
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 5;
						UIposition[] = {0.579999983310699, 0.300000011920929};
						turret[] = {0};
						mirroredMissilePos = 1;
					};
				};
			};
		};
		class ViewOptics: ViewOptics
		{
			visionMode[] = {"Normal", "NVG"};
			thermalMode[] = {};
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; }; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; private _mags = compatibleMagazines _w; { private _t = _x; _v removeWeaponTurret [_w, _t]; { _v removeMagazinesTurret [_x, _t] } forEach _mags } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};

	class OFCRA_CC4_O_B_T_UAV_03_dynamicLoadout_F: OFCRA_CC4_ti4_B_T_UAV_03_dynamicLoadout_F
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_UAV_AI";
		typicalCargo[] = {"O_UAV_AI"};
		displayName = "MQ-12 Falcon (no pylons)";
		textureList[] = {};   // the vehicle's own textures
		class Components: Components
		{
			class TransportPylonsComponent
			{
				UIPicture = "\A3\Air_F_Exp\UAV_03\Data\UI\Map_UAV_03_3DEN_CA.paa";
				class Pylons
				{
					class Pylons1
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 5;
						UIposition[] = {0.0500000007450581, 0.300000011920929};
						turret[] = {0};
					};
					class Pylons2
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 4;
						UIposition[] = {0.100000001490116, 0.379999995231628};
						turret[] = {0};
					};
					class Pylons3
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 4;
						UIposition[] = {0.529999971389771, 0.379999995231628};
						turret[] = {0};
						mirroredMissilePos = 2;
					};
					class Pylons4
					{
						attachment = "";
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						maxweight = 300;
						priority = 5;
						UIposition[] = {0.579999983310699, 0.300000011920929};
						turret[] = {0};
						mirroredMissilePos = 1;
					};
				};
			};
		};
		class ViewOptics: ViewOptics
		{
			visionMode[] = {"Normal", "NVG"};
			thermalMode[] = {};
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; }; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; private _mags = compatibleMagazines _w; { private _t = _x; _v removeWeaponTurret [_w, _t]; { _v removeMagazinesTurret [_x, _t] } forEach _mags } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};
};
