// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for uav03_falcon - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_uav03_falcon
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_B_T_UAV_03_dynamicLoadout_F",
			"OFCRA_CC4_O_B_T_UAV_03_dynamicLoadout_F"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_uav03_falcon",
			"A3_Air_F_Exp_UAV_03"
		};
	};
};

class CfgVehicles
{
	class UAV_03_dynamicLoadout_base_F;
	class B_T_UAV_03_dynamicLoadout_F: UAV_03_dynamicLoadout_base_F
	{
		class EventHandlers;
		class Components;
	};

	class OFCRA_CC4_B_B_T_UAV_03_dynamicLoadout_F: B_T_UAV_03_dynamicLoadout_F
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_UAV_AI";
		typicalCargo[] = {"B_UAV_AI"};
		displayName = "MQ-12 Falcon (no pylons)";
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav03_falcon\uav03_falcon_0.paa",
			"ofcra_cc4\uav03_falcon\uav03_falcon_1.paa",
			"ofcra_cc4\uav03_falcon\uav03_falcon_2.paa"
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				uiPicture = "\A3\Air_F_Exp\UAV_03\Data\UI\Map_UAV_03_3DEN_CA.paa";
				class Pylons
				{
					class Pylons1
					{
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						priority = 5;
						turret[] = {0};
						maxweight = 300;
						UIposition[] = {0.0500000007450581, 0.300000011920929};
						attachment = "";
					};
					class Pylons2: Pylons1
					{
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						priority = 4;
						maxweight = 300;
						UIposition[] = {0.100000001490116, 0.379999995231628};
						attachment = "";
					};
					class Pylons3: Pylons2
					{
						UIposition[] = {0.529999971389771, 0.379999995231628};
						mirroredMissilePos = 2;
						attachment = "";
					};
					class Pylons4: Pylons1
					{
						UIposition[] = {0.579999983310699, 0.300000011920929};
						mirroredMissilePos = 1;
						attachment = "";
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; { _v removeWeaponTurret [_w, _x] } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};

	class OFCRA_CC4_O_B_T_UAV_03_dynamicLoadout_F: B_T_UAV_03_dynamicLoadout_F
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_UAV_AI";
		typicalCargo[] = {"O_UAV_AI"};
		displayName = "MQ-12 Falcon (no pylons)";
		textureList[] = {};   // the vehicle's own textures
		class Components: Components
		{
			class TransportPylonsComponent
			{
				uiPicture = "\A3\Air_F_Exp\UAV_03\Data\UI\Map_UAV_03_3DEN_CA.paa";
				class Pylons
				{
					class Pylons1
					{
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						priority = 5;
						turret[] = {0};
						maxweight = 300;
						UIposition[] = {0.0500000007450581, 0.300000011920929};
						attachment = "";
					};
					class Pylons2: Pylons1
					{
						hardpoints[] = {"DAR", "DAGR", "B_SHIEKER", "UNI_SCALPEL"};
						priority = 4;
						maxweight = 300;
						UIposition[] = {0.100000001490116, 0.379999995231628};
						attachment = "";
					};
					class Pylons3: Pylons2
					{
						UIposition[] = {0.529999971389771, 0.379999995231628};
						mirroredMissilePos = 2;
						attachment = "";
					};
					class Pylons4: Pylons1
					{
						UIposition[] = {0.579999983310699, 0.300000011920929};
						mirroredMissilePos = 1;
						attachment = "";
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; { _v removeWeaponTurret [_w, _x] } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};
};
