// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 38: mkk_boxer_m2_base (OFCRA_CC4) - spawnable: mkk_boxer_m2_b, mkk_boxer_m2_g, mkk_boxer_m2_r
// vehicles.txt line 38: mkk_boxer_gmw_base (OFCRA_CC4) - spawnable: mkk_boxer_gmw_b, mkk_boxer_gmw_g, mkk_boxer_gmw_r
// vehicles.txt line 38: mkk_boxer_ranger_base (OFCRA_CC4) - spawnable: mkk_boxer_ranger_b, mkk_boxer_ranger_g, mkk_boxer_ranger_r
// vehicles.txt line 38: mkk_boxer_base (OFCRA_CC4) - spawnable: mkk_boxer_gmw_b, mkk_boxer_gmw_g, mkk_boxer_gmw_r, mkk_boxer_ifv_b, mkk_boxer_ifv_g, mkk_boxer_ifv_r, ...
// vehicles.txt line 38: mkk_boxer_mgs_base (OFCRA_CC4) - spawnable: mkk_boxer_mgs_b, mkk_boxer_mgs_g, mkk_boxer_mgs_r
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_boxer
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"boxer_c"
		};
	};
};

class CfgVehicles
{
	class Wheeled_APC_F;

	class mkk_boxer_base: Wheeled_APC_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\boxer\boxer_0.paa",
					"ofcra_cc4\boxer\boxer_1.paa",
					"ofcra_cc4\boxer\boxer_2.paa"
				};
				factions[] = {};
			};
		};
	};

	class mkk_boxer_gmw_base: mkk_boxer_base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\boxer\boxer_0.paa",
					"ofcra_cc4\boxer\boxer_1.paa",
					"ofcra_cc4\boxer\boxer_2.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class mkk_boxer_m2_base: mkk_boxer_base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\boxer\boxer_0.paa",
					"ofcra_cc4\boxer\boxer_1.paa",
					"ofcra_cc4\boxer\boxer_2.paa",
					"",
					""
				};
				factions[] = {};
			};
		};
	};

	class mkk_boxer_mgs_base: mkk_boxer_base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\boxer\boxer_0.paa",
					"ofcra_cc4\boxer\boxer_1.paa",
					"ofcra_cc4\boxer\boxer_2.paa"
				};
				factions[] = {};
			};
		};
	};

	class mkk_boxer_ranger_base: mkk_boxer_base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\boxer\boxer_0.paa",
					"ofcra_cc4\boxer\boxer_1.paa",
					"ofcra_cc4\boxer\boxer_2.paa"
				};
				factions[] = {};
			};
		};
	};
};
