// Generated by Build-CC4Faction.ps1
// The CC4 factions. The vehicles are in the subfolders, one config per vehicle and mod.

class CfgPatches
{
	class ofcra_cc4_faction
	{
		author = "OFCRA Wombat";
		units[] = {};
		weapons[] = {};
		requiredAddons[] = {"A3_Data_F"};
	};
};

class CfgFactionClasses
{
	class OFCRA_CC4_B
	{
		displayName = "CC4 Blufor";
		side = 1;
		priority = 1;
	};
	class OFCRA_CC4_O
	{
		displayName = "CC4 Opfor";
		side = 0;
		priority = 1;
	};
};
