// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for uav02_greyhawk - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_uav02_greyhawk
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_B_UAV_02_dynamicLoadout_F",
			"OFCRA_CC4_O_O_UAV_02_dynamicLoadout_F"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_uav02_greyhawk",
			"A3_Drones_F_Air_F_Gamma_UAV_02"
		};
	};
};

class CfgVehicles
{
	class UAV_02_dynamicLoadout_base_F;
	class B_UAV_02_dynamicLoadout_F: UAV_02_dynamicLoadout_base_F
	{
		class EventHandlers;
		class Components;
		class ViewOptics;
		class Turrets;
	};
	class OFCRA_CC4_ti2_B_UAV_02_dynamicLoadout_F: B_UAV_02_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret;
		};
	};
	class OFCRA_CC4_ti3_B_UAV_02_dynamicLoadout_F: OFCRA_CC4_ti2_B_UAV_02_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn;
			};
		};
	};
	class OFCRA_CC4_ti4_B_UAV_02_dynamicLoadout_F: OFCRA_CC4_ti3_B_UAV_02_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide;
					class Medium;
					class Narrow;
				};
			};
		};
	};
	class O_UAV_02_dynamicLoadout_F: UAV_02_dynamicLoadout_base_F
	{
		class EventHandlers;
		class Components;
		class ViewOptics;
		class Turrets;
	};
	class OFCRA_CC4_ti2_O_UAV_02_dynamicLoadout_F: O_UAV_02_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret;
		};
	};
	class OFCRA_CC4_ti3_O_UAV_02_dynamicLoadout_F: OFCRA_CC4_ti2_O_UAV_02_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn;
			};
		};
	};
	class OFCRA_CC4_ti4_O_UAV_02_dynamicLoadout_F: OFCRA_CC4_ti3_O_UAV_02_dynamicLoadout_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class ViewOptics: ViewOptics
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide;
					class Medium;
					class Narrow;
				};
			};
		};
	};

	class OFCRA_CC4_B_B_UAV_02_dynamicLoadout_F: OFCRA_CC4_ti4_B_UAV_02_dynamicLoadout_F
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_UAV_AI";
		typicalCargo[] = {"B_UAV_AI"};
		textureList[] = {"OFCRA_CC4_db", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_db.paa"
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				class pylons
				{
					class pylons1
					{
						attachment = "";
					};
					class pylons2
					{
						attachment = "";
					};
				};
			};
		};
		class ViewOptics: ViewOptics
		{
			visionMode[] = {"Normal", "NVG"};
			thermalMode[] = {};
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; }; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; private _mags = compatibleMagazines _w; { private _t = _x; _v removeWeaponTurret [_w, _t]; { _v removeMagazinesTurret [_x, _t] } forEach _mags } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};

	class OFCRA_CC4_O_O_UAV_02_dynamicLoadout_F: OFCRA_CC4_ti4_O_UAV_02_dynamicLoadout_F
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_UAV_AI";
		typicalCargo[] = {"O_UAV_AI"};
		textureList[] = {"OFCRA_CC4_olive", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_olive.paa"
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				UIPicture = "\a3\Drones_F\Air_F_Gamma\UAV_02\data\ui\UAV_02_base_EDEN_F.paa";
				class pylons
				{
					class pylons1
					{
						hardpoints[] = {"O_BOMB_PYLON", "O_MISSILE_PYLON", "UNI_SCALPEL"};
						attachment = "";
					};
					class pylons2
					{
						hardpoints[] = {"O_BOMB_PYLON", "O_MISSILE_PYLON", "UNI_SCALPEL"};
						UIposition[] = {0.330000013113022, 0.150000005960464};
						mirroredMissilePos = 1;
						attachment = "";
					};
				};
			};
		};
		class ViewOptics: ViewOptics
		{
			visionMode[] = {"Normal", "NVG"};
			thermalMode[] = {};
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; }; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; private _mags = compatibleMagazines _w; { private _t = _x; _v removeWeaponTurret [_w, _t]; { _v removeMagazinesTurret [_x, _t] } forEach _mags } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};
};
