// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for matv - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_matv
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_rhsusf_m1245_m2crows_socom_d",
			"OFCRA_CC4_O_rhsusf_m1245_m2crows_socom_d"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_matv",
			"rhsusf_c_MATV"
		};
	};
};

class CfgVehicles
{
	class rhsusf_MATV_SOF_CROWS_M2_base;
	class rhsusf_m1245_m2crows_socom_d: rhsusf_MATV_SOF_CROWS_M2_base
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_rhsusf_m1245_m2crows_socom_d: rhsusf_m1245_m2crows_socom_d
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\matv\matv_0.paa",
			"ofcra_cc4\matv\matv_1.paa",
			"ofcra_cc4\matv\matv_2.paa",
			"\rhsusf\addons\rhsusf_matv\data\rhsusf_matv_decal_ca.paa",
			"ofcra_cc4\matv\matv_4.paa",
			"ofcra_cc4\matv\matv_5.paa",
			"ofcra_cc4\matv\matv_6.paa",
			"ofcra_cc4\matv\matv_7.paa",
			"ofcra_cc4\matv\matv_8.paa",
			"\rhsusf\addons\rhsusf_matv\data\rhsusf_matva1qnet_wd_ca.paa",
			"ofcra_cc4\matv\matv_10.paa",
			"\a3\map_vr\data\picturemap_ca.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_rhsusf_m1245_m2crows_socom_d: rhsusf_m1245_m2crows_socom_d
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\matv\matv_0.paa",
			"ofcra_cc4\matv\matv_1.paa",
			"ofcra_cc4\matv\matv_2.paa",
			"\rhsusf\addons\rhsusf_matv\data\rhsusf_matv_decal_ca.paa",
			"ofcra_cc4\matv\matv_4.paa",
			"ofcra_cc4\matv\matv_5.paa",
			"ofcra_cc4\matv\matv_6.paa",
			"ofcra_cc4\matv\matv_7.paa",
			"ofcra_cc4\matv\matv_8.paa",
			"\rhsusf\addons\rhsusf_matv\data\rhsusf_matva1qnet_wd_ca.paa",
			"ofcra_cc4\matv\matv_10.paa",
			"\a3\map_vr\data\picturemap_ca.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
