// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 17: UK3CB_Dingo (OFCRA_CC4) - spawnable: UK3CB_AAF_B_Dingo, UK3CB_ION_B_Desert_Dingo, UK3CB_ION_B_Urban_Dingo, UK3CB_ION_B_Winter_Dingo, UK3CB_ION_B_Woodland_Dingo, UK3CB_ION_I_Desert_Dingo, ...
// vehicles.txt line 17: UK3CB_Dingo_GMG (OFCRA_CC4) - spawnable: UK3CB_AAF_B_Dingo_GMG, UK3CB_ION_B_Desert_Dingo_GMG, UK3CB_ION_B_Urban_Dingo_GMG, UK3CB_ION_B_Winter_Dingo_GMG, UK3CB_ION_B_Woodland_Dingo_GMG, UK3CB_ION_I_Desert_Dingo_GMG, ...
// vehicles.txt line 17: UK3CB_Dingo_HMG (OFCRA_CC4) - spawnable: UK3CB_AAF_B_Dingo_HMG, UK3CB_ION_B_Desert_Dingo_HMG, UK3CB_ION_B_Urban_Dingo_HMG, UK3CB_ION_B_Winter_Dingo_HMG, UK3CB_ION_B_Woodland_Dingo_HMG, UK3CB_ION_I_Desert_Dingo_HMG, ...
// vehicles.txt line 17: UK3CB_Dingo_MG3 (OFCRA_CC4) - spawnable: UK3CB_AAF_B_Dingo_MG3, UK3CB_ION_B_Desert_Dingo_MG3, UK3CB_ION_B_Urban_Dingo_MG3, UK3CB_ION_B_Winter_Dingo_MG3, UK3CB_ION_B_Woodland_Dingo_MG3, UK3CB_ION_I_Desert_Dingo_MG3, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_dingo
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Dingo"
		};
	};
};

class CfgVehicles
{
	class UK3CB_Dingo_Base;

	class UK3CB_Dingo: UK3CB_Dingo_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\dingo\dingo_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\a_teile_ion_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\innen_teile2_co.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_Dingo_GMG: UK3CB_Dingo_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\dingo\dingo_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\a_teile_ion_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\innen_teile2_co.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_Dingo_HMG: UK3CB_Dingo_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\dingo\dingo_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\a_teile_ion_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\innen_teile2_co.paa",
					"",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_Dingo_MG3: UK3CB_Dingo_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\dingo\dingo_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\a_teile_ion_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\innen_teile2_co.paa",
					""
				};
				factions[] = {};
			};
		};
	};
};
