// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// landrover is split by required addons (2 configs) so a missing mod only skips its own part
// vehicles.txt line 21: UK3CB_LandRover_WMIK (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_WMIK_FFV, UK3CB_AAF_B_LR_WMIK_M2, UK3CB_AAF_B_LR_WMIK_M240, UK3CB_AAF_B_LR_WMIK_MG3, UK3CB_AAF_B_LR_WMIK_MK19, UK3CB_AAF_I_LR_WMIK_FFV, ...
// vehicles.txt line 23: UK3CB_LandRover_SF_WMIK_Base (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_SF_WMIK_FFV, UK3CB_AAF_B_LR_SF_WMIK_M240_M240, UK3CB_AAF_B_LR_SF_WMIK_M2_M240, UK3CB_AAF_B_LR_SF_WMIK_MILAN_M240, UK3CB_AAF_B_LR_SF_WMIK_MK19_M240, UK3CB_AAF_I_LR_SF_WMIK_FFV, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_landrover_uk3cb_factions_vehicles_landrover_wmik
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_LandRover_WMIK"
		};
	};
};

class CfgVehicles
{
	class UK3CB_LandRover_WMIK_Base;

	class UK3CB_LandRover_SF_WMIK_Base: UK3CB_LandRover_WMIK_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_WMIK: UK3CB_LandRover_WMIK_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
				};
				factions[] = {};
			};
		};
	};
};
