// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 27: UK3CB_Orca_Armed (OFCRA_CC4) - spawnable: UK3CB_CSAT_A_O_Orca_Armed_AT, UK3CB_CSAT_A_O_Orca_Armed_CAS, UK3CB_CSAT_A_O_Orca_Armed_MULTI, UK3CB_CSAT_B_O_Orca_Armed_AT, UK3CB_CSAT_B_O_Orca_Armed_CAS, UK3CB_CSAT_B_O_Orca_Armed_MULTI, ...
// vehicles.txt line 27: UK3CB_Orca_Unarmed (OFCRA_CC4) - spawnable: UK3CB_CSAT_A_O_Orca, UK3CB_CSAT_B_O_Orca, UK3CB_CSAT_F_O_Orca, UK3CB_CSAT_G_O_Orca, UK3CB_CSAT_M_O_Orca, UK3CB_CSAT_N_O_Orca, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_orca
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Orca"
		};
	};
};

class CfgVehicles
{
	class Heli_Light_02_dynamicLoadout_base_F;
	class Heli_Light_02_unarmed_base_F;

	class UK3CB_Orca_Armed: Heli_Light_02_dynamicLoadout_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\orca\orca_0.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_Orca_Unarmed: Heli_Light_02_unarmed_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\orca\orca_0.paa"
				};
				factions[] = {};
			};
		};
	};
};
