// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 15: UK3CB_M1025_Unarmed_Base (OFCRA_CC4) - spawnable: UK3CB_AAF_B_M1025, UK3CB_ABP_B_M1025, UK3CB_ANA_B_M1025, UK3CB_ANP_B_M1025, UK3CB_CW_US_B_LATE_M1025_Unarmed, UK3CB_ION_B_Desert_M1025, ...
// vehicles.txt line 15: UK3CB_M1025_TOW_Base (OFCRA_CC4) - spawnable: UK3CB_AAF_B_M1025_TOW, UK3CB_CW_US_B_LATE_M1025_TOW, UK3CB_ION_B_Desert_M1025_TOW, UK3CB_ION_B_Urban_M1025_TOW, UK3CB_ION_B_Winter_M1025_TOW, UK3CB_ION_B_Woodland_M1025_TOW, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_hmmwv
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_HMMWV"
		};
	};
};

class CfgVehicles
{
	class rhsusf_m998_w_4dr_fulltop;
	class rhsusf_m1025_w: rhsusf_m998_w_4dr_fulltop
	{
		class TextureSources;
	};
	class rhsusf_m966_w: rhsusf_m1025_w
	{
		class TextureSources;
	};

	class UK3CB_M1025_Unarmed_Base: rhsusf_m1025_w
	{
		class TextureSources: TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_exterior_co.paa",
					"\rhsusf\addons\rhsusf_hmmwv\textures\m998_interior_d_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_a2_parts_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_wheel_wranglermt_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_mainbody_co.paa",
					"\rhsusf\addons\rhsusf_hmmwv\textures\gratting_w_co.paa",
					"\rhsusf\addons\rhsusf_hmmwv\textures\tile_exmetal_co.paa",
					"ofcra_cc4\hmmwv\hmmwv_7.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_M1025_TOW_Base: rhsusf_m966_w
	{
		class TextureSources: TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_exterior_co.paa",
					"\rhsusf\addons\rhsusf_hmmwv\textures\m998_interior_d_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_a2_parts_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_wheel_wranglermt_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_mainbody_co.paa",
					"\rhsusf\addons\rhsusf_hmmwv\textures\gratting_w_co.paa",
					"\rhsusf\addons\rhsusf_hmmwv\textures\tile_exmetal_co.paa",
					"ofcra_cc4\hmmwv\hmmwv_7.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa",
					"",
					"",
					"",
					""
				};
				factions[] = {};
			};
		};
	};
};
