// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for quadbike - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_quadbike
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_AAF_B_Quadbike",
			"OFCRA_CC4_O_UK3CB_AAF_O_Quadbike"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_quadbike",
			"UK3CB_Factions_AAF_B",
			"UK3CB_Factions_AAF_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_B_Quadbike_AAF;
	class UK3CB_O_Quadbike_AAF;
	class UK3CB_AAF_B_Quadbike: UK3CB_B_Quadbike_AAF
	{
		class EventHandlers;
	};
	class UK3CB_AAF_O_Quadbike: UK3CB_O_Quadbike_AAF
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_Quadbike: UK3CB_AAF_B_Quadbike
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\quadbike\quadbike_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_quadbike\data\ion_quadbike_01_wheel_co.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_AAF_O_Quadbike: UK3CB_AAF_O_Quadbike
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\quadbike\quadbike_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_quadbike\data\ion_quadbike_01_wheel_co.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
