// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// ugv01_stomper is split by required addons (2 configs) so a missing mod only skips its own part
// vehicles.txt line 42: UK3CB_UGV_Armed_base (OFCRA_CC4) - spawnable: UK3CB_CSAT_A_O_UGV_Armed, UK3CB_CSAT_B_O_UGV_Armed, UK3CB_CSAT_F_O_UGV_Armed, UK3CB_CSAT_G_O_UGV_Armed, UK3CB_CSAT_M_O_UGV_Armed, UK3CB_CSAT_N_O_UGV_Armed, ...
// vehicles.txt line 42: UK3CB_UGV_Armed_base (OFCRA_CC4_db) - spawnable: UK3CB_CSAT_A_O_UGV_Armed, UK3CB_CSAT_B_O_UGV_Armed, UK3CB_CSAT_F_O_UGV_Armed, UK3CB_CSAT_G_O_UGV_Armed, UK3CB_CSAT_M_O_UGV_Armed, UK3CB_CSAT_N_O_UGV_Armed, ...
// vehicles.txt line 42: UK3CB_UGV_Armed_base (OFCRA_CC4_olive) - spawnable: UK3CB_CSAT_A_O_UGV_Armed, UK3CB_CSAT_B_O_UGV_Armed, UK3CB_CSAT_F_O_UGV_Armed, UK3CB_CSAT_G_O_UGV_Armed, UK3CB_CSAT_M_O_UGV_Armed, UK3CB_CSAT_N_O_UGV_Armed, ...
// vehicles.txt line 42: UK3CB_UGV_Unarmed_base (OFCRA_CC4) - spawnable: UK3CB_CSAT_A_O_UGV_Unarmed, UK3CB_CSAT_B_O_UGV_Unarmed, UK3CB_CSAT_F_O_UGV_Unarmed, UK3CB_CSAT_G_O_UGV_Unarmed, UK3CB_CSAT_M_O_UGV_Unarmed, UK3CB_CSAT_N_O_UGV_Unarmed, ...
// vehicles.txt line 42: UK3CB_UGV_Unarmed_base (OFCRA_CC4_db) - spawnable: UK3CB_CSAT_A_O_UGV_Unarmed, UK3CB_CSAT_B_O_UGV_Unarmed, UK3CB_CSAT_F_O_UGV_Unarmed, UK3CB_CSAT_G_O_UGV_Unarmed, UK3CB_CSAT_M_O_UGV_Unarmed, UK3CB_CSAT_N_O_UGV_Unarmed, ...
// vehicles.txt line 42: UK3CB_UGV_Unarmed_base (OFCRA_CC4_olive) - spawnable: UK3CB_CSAT_A_O_UGV_Unarmed, UK3CB_CSAT_B_O_UGV_Unarmed, UK3CB_CSAT_F_O_UGV_Unarmed, UK3CB_CSAT_G_O_UGV_Unarmed, UK3CB_CSAT_M_O_UGV_Unarmed, UK3CB_CSAT_N_O_UGV_Unarmed, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_db", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_olive", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_ugv01_stomper_uk3cb_factions_vehicles_stomper
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Stomper"
		};
	};
};

class CfgVehicles
{
	class O_UGV_01_F;
	class UGV_01_rcws_base_F;

	class UK3CB_UGV_Armed_base: UGV_01_rcws_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_db
			{
				displayName = "OFCRA CC4 Dark Brown";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_db.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_db.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_db.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_olive
			{
				displayName = "OFCRA CC4 Olive";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_olive.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_olive.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_olive.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_UGV_Unarmed_base: O_UGV_01_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_db
			{
				displayName = "OFCRA CC4 Dark Brown";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_db.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_db.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_db.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_olive
			{
				displayName = "OFCRA CC4 Olive";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_olive.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_olive.paa",
					"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_olive.paa"
				};
				factions[] = {};
			};
		};
	};
};
