// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 34: cv_9030_base_Tank_F (OFCRA_CC4) - spawnable: mkk_cv9030, mkk_cv_9030_g, mkk_cv_9030_r
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_cv9030
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"mkk_cv_9030"
		};
	};
};

class CfgVehicles
{
	class Tank_F;

	class cv_9030_base_Tank_F: Tank_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\cv9030\cv9030_0.paa",
					"ofcra_cc4\cv9030\cv9030_1.paa",
					"ofcra_cc4\cv9030\cv9030_2.paa",
					"ofcra_cc4\cv9030\cv9030_3.paa",
					"\bmp_2m\data\rifled_barrel_b_co.paa",
					"\t_64_b_bv\data\mg_pkt_co.paa",
					"\cv_9030\data\strf_90c_track_co.paa"
				};
				factions[] = {};
			};
		};
	};
};
