// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for tiger - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_tiger
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_BWA3_Tiger",
			"OFCRA_CC4_O_BWA3_Tiger"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_tiger",
			"bwa3_tiger",
			"A3_Weapons_F",
			"rhs_c_airweapons"
		};
	};
};

class CfgVehicles
{
	class BWA3_Tiger_base;
	class BWA3_Tiger: BWA3_Tiger_base
	{
		class EventHandlers;
		class Components;
		class Turrets;
	};
	class OFCRA_CC4_ti2_BWA3_Tiger: BWA3_Tiger
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class Turrets: Turrets
		{
			class MainTurret;
		};
	};
	class OFCRA_CC4_ti3_BWA3_Tiger: OFCRA_CC4_ti2_BWA3_Tiger
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn;
			};
		};
	};
	class OFCRA_CC4_ti4_BWA3_Tiger: OFCRA_CC4_ti3_BWA3_Tiger
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Components: Components
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide;
					class Medium;
					class Narrow;
				};
			};
		};
	};

	class OFCRA_CC4_B_BWA3_Tiger: OFCRA_CC4_ti4_BWA3_Tiger
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Helipilot_F";
		typicalCargo[] = {"B_Helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\tiger\tiger_0.paa",
			"ofcra_cc4\tiger\tiger_1.paa",
			"ofcra_cc4\tiger\tiger_2.paa",
			"ofcra_cc4\tiger\tiger_3.paa",
			"\bwa3_tiger\data\symbols\3_ca.paa",
			"\bwa3_tiger\data\symbols\0_ca.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				UIPicture = "\bwa3_tiger\ui\bwa3_tiger_3DEN_ca.paa";
				class Pylons
				{
					class PylonLeft1
					{
						attachment = "PylonRack_7Rnd_Rocket_04_AP_F";
						hardpoints[] = {"BWA3_Outer_Pylon", "OFCRA_CC4_tiger"};
						priority = 5;
						UIposition[] = {0.119999997317791, 0.430000007152557};
						turret[] = {};
						name = "Tiger_Attack_01";
					};
					class PylonLeft2
					{
						attachment = "rhs_mag_upk23_btz";
						hardpoints[] = {"BWA3_Inner_Pylon", "OFCRA_CC4_tiger"};
						priority = 3;
						UIposition[] = {0.200000002980232, 0.379999995231628};
						turret[] = {};
						name = "Tiger_Attack_01";
					};
					class PylonRight2
					{
						attachment = "";
						hardpoints[] = {"BWA3_Inner_Pylon"};
						priority = 3;
						UIposition[] = {0.465000003576279, 0.379999995231628};
						turret[] = {0};
						mirroredMissilePos = 2;
						name = "Tiger_Attack_01";
					};
					class PylonRight1
					{
						attachment = "";
						hardpoints[] = {"BWA3_Outer_Pylon"};
						priority = 5;
						UIposition[] = {0.545000016689301, 0.430000007152557};
						turret[] = {};
						mirroredMissilePos = 1;
						name = "Tiger_Attack_01";
					};
				};
			};
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};

	class OFCRA_CC4_O_BWA3_Tiger: OFCRA_CC4_ti4_BWA3_Tiger
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_helipilot_F";
		typicalCargo[] = {"O_helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\tiger\tiger_0.paa",
			"ofcra_cc4\tiger\tiger_1.paa",
			"ofcra_cc4\tiger\tiger_2.paa",
			"ofcra_cc4\tiger\tiger_3.paa",
			"\bwa3_tiger\data\symbols\3_ca.paa",
			"\bwa3_tiger\data\symbols\0_ca.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				UIPicture = "\bwa3_tiger\ui\bwa3_tiger_3DEN_ca.paa";
				class Pylons
				{
					class PylonLeft1
					{
						attachment = "PylonRack_7Rnd_Rocket_04_AP_F";
						hardpoints[] = {"BWA3_Outer_Pylon", "OFCRA_CC4_tiger"};
						priority = 5;
						UIposition[] = {0.119999997317791, 0.430000007152557};
						turret[] = {};
						name = "Tiger_Attack_01";
					};
					class PylonLeft2
					{
						attachment = "rhs_mag_upk23_btz";
						hardpoints[] = {"BWA3_Inner_Pylon", "OFCRA_CC4_tiger"};
						priority = 3;
						UIposition[] = {0.200000002980232, 0.379999995231628};
						turret[] = {};
						name = "Tiger_Attack_01";
					};
					class PylonRight2
					{
						attachment = "";
						hardpoints[] = {"BWA3_Inner_Pylon"};
						priority = 3;
						UIposition[] = {0.465000003576279, 0.379999995231628};
						turret[] = {0};
						mirroredMissilePos = 2;
						name = "Tiger_Attack_01";
					};
					class PylonRight1
					{
						attachment = "";
						hardpoints[] = {"BWA3_Outer_Pylon"};
						priority = 5;
						UIposition[] = {0.545000016689301, 0.430000007152557};
						turret[] = {};
						mirroredMissilePos = 1;
						name = "Tiger_Attack_01";
					};
				};
			};
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};
};

class CfgMagazines
{
	class 7Rnd_Rocket_04_AP_F;
	class rhs_mag_upk23_ofz;
	class PylonRack_7Rnd_Rocket_04_AP_F: 7Rnd_Rocket_04_AP_F
	{
		hardpoints[] = {"B_MISSILE_PYLON", "B_SHIEKER", "OFCRA_CC4_tiger"};
	};
	class rhs_mag_upk23_btz: rhs_mag_upk23_ofz
	{
		hardpoints[] = {"RHS_HP_UPK23", "OFCRA_CC4_tiger"};
	};
};
