// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for tiger - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_tiger
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_BWA3_Tiger",
			"OFCRA_CC4_O_BWA3_Tiger"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_tiger",
			"bwa3_tiger",
			"A3_Weapons_F",
			"rhs_c_airweapons"
		};
	};
};

class CfgVehicles
{
	class BWA3_Tiger_base;
	class BWA3_Tiger: BWA3_Tiger_base
	{
		class EventHandlers;
		class Components;
	};

	class OFCRA_CC4_B_BWA3_Tiger: BWA3_Tiger
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Helipilot_F";
		typicalCargo[] = {"B_Helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\tiger\tiger_0.paa",
			"ofcra_cc4\tiger\tiger_1.paa",
			"ofcra_cc4\tiger\tiger_2.paa",
			"ofcra_cc4\tiger\tiger_3.paa",
			"\bwa3_tiger\data\symbols\3_ca.paa",
			"\bwa3_tiger\data\symbols\0_ca.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				uiPicture = "\bwa3_tiger\ui\bwa3_tiger_3DEN_ca.paa";
				class Pylons
				{
					class PylonLeft1
					{
						priority = 5;
						turret[] = {};
						UIposition[] = {0.119999997317791, 0.430000007152557};
						name = "Tiger_Attack_01";
						attachment = "PylonRack_7Rnd_Rocket_04_AP_F";
						hardpoints[] = {"BWA3_Outer_Pylon", "OFCRA_CC4_tiger"};
					};
					class PylonLeft2: PylonLeft1
					{
						priority = 3;
						turret[] = {};
						UIposition[] = {0.200000002980232, 0.379999995231628};
						attachment = "rhs_mag_upk23_btz";
						hardpoints[] = {"BWA3_Inner_Pylon", "OFCRA_CC4_tiger"};
					};
					class PylonRight2: PylonLeft2
					{
						attachment = "Pylonweapon_4Rnd_PARS";
						priority = 3;
						turret[] = {0};
						mirroredMissilePos = 2;
						UIposition[] = {0.465000003576279, 0.379999995231628};
					};
					class PylonRight1: PylonLeft1
					{
						attachment = "Pylonweapon_2Rnd_Fliegerfaust";
						priority = 5;
						mirroredMissilePos = 1;
						turret[] = {};
						UIposition[] = {0.545000016689301, 0.430000007152557};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_BWA3_Tiger: BWA3_Tiger
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_helipilot_F";
		typicalCargo[] = {"O_helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\tiger\tiger_0.paa",
			"ofcra_cc4\tiger\tiger_1.paa",
			"ofcra_cc4\tiger\tiger_2.paa",
			"ofcra_cc4\tiger\tiger_3.paa",
			"\bwa3_tiger\data\symbols\3_ca.paa",
			"\bwa3_tiger\data\symbols\0_ca.paa",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"#(argb,8,8,3)color(0,0,0,0,co)",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class Components: Components
		{
			class TransportPylonsComponent
			{
				uiPicture = "\bwa3_tiger\ui\bwa3_tiger_3DEN_ca.paa";
				class Pylons
				{
					class PylonLeft1
					{
						priority = 5;
						turret[] = {};
						UIposition[] = {0.119999997317791, 0.430000007152557};
						name = "Tiger_Attack_01";
						attachment = "PylonRack_7Rnd_Rocket_04_AP_F";
						hardpoints[] = {"BWA3_Outer_Pylon", "OFCRA_CC4_tiger"};
					};
					class PylonLeft2: PylonLeft1
					{
						priority = 3;
						turret[] = {};
						UIposition[] = {0.200000002980232, 0.379999995231628};
						attachment = "rhs_mag_upk23_btz";
						hardpoints[] = {"BWA3_Inner_Pylon", "OFCRA_CC4_tiger"};
					};
					class PylonRight2: PylonLeft2
					{
						attachment = "Pylonweapon_4Rnd_PARS";
						priority = 3;
						turret[] = {0};
						mirroredMissilePos = 2;
						UIposition[] = {0.465000003576279, 0.379999995231628};
					};
					class PylonRight1: PylonLeft1
					{
						attachment = "Pylonweapon_2Rnd_Fliegerfaust";
						priority = 5;
						mirroredMissilePos = 1;
						turret[] = {};
						UIposition[] = {0.545000016689301, 0.430000007152557};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};

class CfgMagazines
{
	class 7Rnd_Rocket_04_AP_F;
	class rhs_mag_upk23_ofz;
	class PylonRack_7Rnd_Rocket_04_AP_F: 7Rnd_Rocket_04_AP_F
	{
		hardpoints[] = {"B_MISSILE_PYLON", "B_SHIEKER", "OFCRA_CC4_tiger"};
	};
	class rhs_mag_upk23_btz: rhs_mag_upk23_ofz
	{
		hardpoints[] = {"RHS_HP_UPK23", "OFCRA_CC4_tiger"};
	};
};
