// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 21: UK3CB_LandRover_Softtop_Transport_Closed (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_Softtop_Transport_Closed, UK3CB_AAF_B_LR_Softtop_Transport_Open, UK3CB_AAF_I_LR_Softtop_Transport_Closed, UK3CB_AAF_I_LR_Softtop_Transport_Open, UK3CB_AAF_O_LR_Softtop_Transport_Closed, UK3CB_AAF_O_LR_Softtop_Transport_Open, ...
// vehicles.txt line 21: UK3CB_LandRover_WMIK (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_WMIK_FFV, UK3CB_AAF_B_LR_WMIK_M2, UK3CB_AAF_B_LR_WMIK_M240, UK3CB_AAF_B_LR_WMIK_MG3, UK3CB_AAF_B_LR_WMIK_MK19, UK3CB_AAF_I_LR_WMIK_FFV, ...
// vehicles.txt line 21: UK3CB_LandRover_Softtop_Ambulance_Closed (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_Softtop_Ambulance_Closed, UK3CB_AAF_B_LR_Softtop_Ambulance_Open, UK3CB_AAF_I_LR_Softtop_Ambulance_Closed, UK3CB_AAF_I_LR_Softtop_Ambulance_Open, UK3CB_AAF_O_LR_Softtop_Ambulance_Closed, UK3CB_AAF_O_LR_Softtop_Ambulance_Open, ...
// vehicles.txt line 21: UK3CB_LandRover_Softtop_Reammo_Closed (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_Softtop_Reammo_Closed, UK3CB_AAF_B_LR_Softtop_Reammo_Open, UK3CB_AAF_I_LR_Softtop_Reammo_Closed, UK3CB_AAF_I_LR_Softtop_Reammo_Open, UK3CB_AAF_O_LR_Softtop_Reammo_Closed, UK3CB_AAF_O_LR_Softtop_Reammo_Open, ...
// vehicles.txt line 21: UK3CB_LandRover_Softtop_Refuel_Closed (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_Softtop_Refuel_Closed, UK3CB_AAF_B_LR_Softtop_Refuel_Open, UK3CB_AAF_I_LR_Softtop_Refuel_Closed, UK3CB_AAF_I_LR_Softtop_Refuel_Open, UK3CB_AAF_O_LR_Softtop_Refuel_Closed, UK3CB_AAF_O_LR_Softtop_Refuel_Open, ...
// vehicles.txt line 21: UK3CB_LandRover_Softtop_Repair_Closed (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_Softtop_Repair_Closed, UK3CB_AAF_B_LR_Softtop_Repair_Open, UK3CB_AAF_I_LR_Softtop_Repair_Closed, UK3CB_AAF_I_LR_Softtop_Repair_Open, UK3CB_AAF_O_LR_Softtop_Repair_Closed, UK3CB_AAF_O_LR_Softtop_Repair_Open, ...
// vehicles.txt line 21: UK3CB_LandRover_Opentop_Base (OFCRA_CC4) - spawnable: UK3CB_AAF_I_LR_Opentop_SPG9, UK3CB_AAF_O_LR_Opentop_SPG9, UK3CB_ADA_B_LR_Opentop_PKM, UK3CB_ADA_B_LR_Opentop_SPG9, UK3CB_ADA_I_LR_Opentop_PKM, UK3CB_ADA_I_LR_Opentop_SPG9, ...
// vehicles.txt line 21: UK3CB_LandRover_Opentop_Ambulance (OFCRA_CC4) - spawnable: UK3CB_ADE_I_LR_Opentop_Ambulance, UK3CB_ADE_O_LR_Opentop_Ambulance, UK3CB_ADG_B_LR_Opentop_Ambulance, UK3CB_ADG_B_LR_Opentop_Ambulance_ISL, UK3CB_ADG_I_LR_Opentop_Ambulance, UK3CB_ADG_I_LR_Opentop_Ambulance_ISL, ...
// vehicles.txt line 21: UK3CB_LandRover_Opentop_Reammo (OFCRA_CC4) - spawnable: UK3CB_ADE_I_LR_Opentop_Reammo, UK3CB_ADE_O_LR_Opentop_Reammo, UK3CB_ADG_B_LR_Opentop_Reammo, UK3CB_ADG_B_LR_Opentop_Reammo_ISL, UK3CB_ADG_I_LR_Opentop_Reammo, UK3CB_ADG_I_LR_Opentop_Reammo_ISL, ...
// vehicles.txt line 21: UK3CB_LandRover_Opentop_Refuel (OFCRA_CC4) - spawnable: UK3CB_ADE_I_LR_Opentop_Refuel, UK3CB_ADE_O_LR_Opentop_Refuel, UK3CB_ADG_B_LR_Opentop_Refuel, UK3CB_ADG_B_LR_Opentop_Refuel_ISL, UK3CB_ADG_I_LR_Opentop_Refuel, UK3CB_ADG_I_LR_Opentop_Refuel_ISL, ...
// vehicles.txt line 21: UK3CB_LandRover_Opentop_Repair (OFCRA_CC4) - spawnable: UK3CB_ADE_I_LR_Opentop_Repair, UK3CB_ADE_O_LR_Opentop_Repair, UK3CB_ADG_B_LR_Opentop_Repair, UK3CB_ADG_B_LR_Opentop_Repair_ISL, UK3CB_ADG_I_LR_Opentop_Repair, UK3CB_ADG_I_LR_Opentop_Repair_ISL, ...
// vehicles.txt line 23: UK3CB_LandRover_SF_WMIK_Base (OFCRA_CC4) - spawnable: UK3CB_AAF_B_LR_SF_WMIK_FFV, UK3CB_AAF_B_LR_SF_WMIK_M240_M240, UK3CB_AAF_B_LR_SF_WMIK_M2_M240, UK3CB_AAF_B_LR_SF_WMIK_MILAN_M240, UK3CB_AAF_B_LR_SF_WMIK_MK19_M240, UK3CB_AAF_I_LR_SF_WMIK_FFV, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_landrover
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_LandRover",
			"UK3CB_Factions_Vehicles_LandRover_WMIK"
		};
	};
};

class CfgVehicles
{
	class UK3CB_LandRover_Base;
	class UK3CB_LandRover_WMIK_Base;

	class UK3CB_LandRover_Opentop_Base: UK3CB_LandRover_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_SF_WMIK_Base: UK3CB_LandRover_WMIK_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
				};
				factions[] = {};
			};
		};
	};
	class UK3CB_LandRover_Softtop_Base;

	class UK3CB_LandRover_WMIK: UK3CB_LandRover_WMIK_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Opentop_Ambulance: UK3CB_LandRover_Opentop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Opentop_Reammo: UK3CB_LandRover_Opentop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Opentop_Refuel: UK3CB_LandRover_Opentop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Opentop_Repair: UK3CB_LandRover_Opentop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Softtop_Ambulance_Closed: UK3CB_LandRover_Softtop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Softtop_Reammo_Closed: UK3CB_LandRover_Softtop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Softtop_Refuel_Closed: UK3CB_LandRover_Softtop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Softtop_Repair_Closed: UK3CB_LandRover_Softtop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_LandRover_Softtop_Transport_Closed: UK3CB_LandRover_Softtop_Base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\landrover\landrover_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
				};
				factions[] = {};
			};
		};
	};
};
