// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for warrior - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_warrior
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_mkk_warrior_b",
			"OFCRA_CC4_O_mkk_warrior_b"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_warrior",
			"warrior_c"
		};
	};
};

class CfgVehicles
{
	class mkk_warrior_base;
	class mkk_warrior_b: mkk_warrior_base
	{
		class EventHandlers;
		class Turrets;
	};
	class OFCRA_CC4_ti2_mkk_warrior_b: mkk_warrior_b
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret;
		};
	};
	class OFCRA_CC4_ti3_mkk_warrior_b: OFCRA_CC4_ti2_mkk_warrior_b
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class ViewOptics;
				class OpticsIn;
				class Turrets;
			};
		};
	};
	class OFCRA_CC4_ti4_mkk_warrior_b: OFCRA_CC4_ti3_mkk_warrior_b
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class ViewOptics: ViewOptics
				{
				};
				class OpticsIn: OpticsIn
				{
					class Wide;
					class Narrow;
					class Narrow2x;
				};
				class Turrets: Turrets
				{
					class CommanderOptics;
				};
			};
		};
	};
	class OFCRA_CC4_ti5_mkk_warrior_b: OFCRA_CC4_ti4_mkk_warrior_b
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class ViewOptics: ViewOptics
				{
				};
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
					};
					class Narrow: Narrow
					{
					};
					class Narrow2x: Narrow2x
					{
					};
				};
				class Turrets: Turrets
				{
					class CommanderOptics: CommanderOptics
					{
						class OpticsIn;
					};
				};
			};
		};
	};
	class OFCRA_CC4_ti6_mkk_warrior_b: OFCRA_CC4_ti5_mkk_warrior_b
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class ViewOptics: ViewOptics
				{
				};
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
					};
					class Narrow: Narrow
					{
					};
					class Narrow2x: Narrow2x
					{
					};
				};
				class Turrets: Turrets
				{
					class CommanderOptics: CommanderOptics
					{
						class OpticsIn: OpticsIn
						{
							class Wide;
							class Narrow;
							class Narrow2x;
						};
					};
				};
			};
		};
	};

	class OFCRA_CC4_B_mkk_warrior_b: OFCRA_CC4_ti6_mkk_warrior_b
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\warrior\warrior_0.paa",
			"ofcra_cc4\warrior\warrior_1.paa",
			"ofcra_cc4\warrior\warrior_2.paa",
			"ofcra_cc4\warrior\warrior_3.paa",
			"ofcra_cc4\warrior\warrior_4.paa",
			"",
			"",
			"",
			""
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class ViewOptics: ViewOptics
				{
					visionMode[] = {"Normal", "NVG"};
					thermalMode[] = {};
				};
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow2x: Narrow2x
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
				class Turrets: Turrets
				{
					class CommanderOptics: CommanderOptics
					{
						class OpticsIn: OpticsIn
						{
							class Wide: Wide
							{
								visionMode[] = {"Normal", "NVG"};
								thermalMode[] = {};
							};
							class Narrow: Narrow
							{
								visionMode[] = {"Normal", "NVG"};
								thermalMode[] = {};
							};
							class Narrow2x: Narrow2x
							{
								visionMode[] = {"Normal", "NVG"};
								thermalMode[] = {};
							};
						};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};

	class OFCRA_CC4_O_mkk_warrior_b: OFCRA_CC4_ti6_mkk_warrior_b
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\warrior\warrior_0.paa",
			"ofcra_cc4\warrior\warrior_1.paa",
			"ofcra_cc4\warrior\warrior_2.paa",
			"ofcra_cc4\warrior\warrior_3.paa",
			"ofcra_cc4\warrior\warrior_4.paa",
			"",
			"",
			"",
			""
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class ViewOptics: ViewOptics
				{
					visionMode[] = {"Normal", "NVG"};
					thermalMode[] = {};
				};
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow2x: Narrow2x
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
				class Turrets: Turrets
				{
					class CommanderOptics: CommanderOptics
					{
						class OpticsIn: OpticsIn
						{
							class Wide: Wide
							{
								visionMode[] = {"Normal", "NVG"};
								thermalMode[] = {};
							};
							class Narrow: Narrow
							{
								visionMode[] = {"Normal", "NVG"};
								thermalMode[] = {};
							};
							class Narrow2x: Narrow2x
							{
								visionMode[] = {"Normal", "NVG"};
								thermalMode[] = {};
							};
						};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};
};
