// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for warrior - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_warrior
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_mkk_warrior_b",
			"OFCRA_CC4_O_mkk_warrior_b"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_warrior",
			"warrior_c"
		};
	};
};

class CfgVehicles
{
	class mkk_warrior_base;
	class mkk_warrior_b: mkk_warrior_base
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_mkk_warrior_b: mkk_warrior_b
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\warrior\warrior_0.paa",
			"ofcra_cc4\warrior\warrior_1.paa",
			"ofcra_cc4\warrior\warrior_2.paa",
			"ofcra_cc4\warrior\warrior_3.paa",
			"ofcra_cc4\warrior\warrior_4.paa",
			"",
			"",
			"",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_mkk_warrior_b: mkk_warrior_b
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\warrior\warrior_0.paa",
			"ofcra_cc4\warrior\warrior_1.paa",
			"ofcra_cc4\warrior\warrior_2.paa",
			"ofcra_cc4\warrior\warrior_3.paa",
			"ofcra_cc4\warrior\warrior_4.paa",
			"",
			"",
			"",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
