// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 19: UK3CB_M113tank_M2 (OFCRA_CC4) - spawnable: UK3CB_ANA_B_M113_M2, UK3CB_FIA_B_M113_M2, UK3CB_FIA_I_M113_M2, UK3CB_FIA_O_M113_M2, UK3CB_ION_B_Desert_M113_M2, UK3CB_ION_B_Urban_M113_M2, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_m113
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_M113"
		};
	};
};

class CfgVehicles
{
	class APC_Tracked_02_base_F;
	class rhsusf_m113tank_base: APC_Tracked_02_base_F
	{
		class TextureSources;
	};

	class UK3CB_M113tank_M2: rhsusf_m113tank_base
	{
		class TextureSources: TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\m113\m113_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_02_h_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_03_co.paa",
					"\rhsusf\addons\rhsusf_m113\data_new\m113a3_int03_d_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m23_pintle_co.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_shield_co.paa"
				};
				factions[] = {};
			};
		};
	};
};
