// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for uav02_greyhawk - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_uav02_greyhawk_air_globe_uav_02
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_B_UAV_02_LM_G",
			"OFCRA_CC4_O_O_UAV_02_LM_G"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_uav02_greyhawk_air_globe_uav_02",
			"Air_Globe_UAV_02"
		};
	};
};

class CfgVehicles
{
	class UAV_02_base_F;
	class B_UAV_02_LM_G: UAV_02_base_F
	{
		class EventHandlers;
	};
	class O_UAV_02_LM_G: B_UAV_02_LM_G
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_B_UAV_02_LM_G: B_UAV_02_LM_G
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_UAV_AI";
		typicalCargo[] = {"B_UAV_AI"};
		textureList[] = {"OFCRA_CC4_db", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_db.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; private _mags = compatibleMagazines _w; { private _t = _x; _v removeWeaponTurret [_w, _t]; { _v removeMagazinesTurret [_x, _t] } forEach _mags } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};

	class OFCRA_CC4_O_O_UAV_02_LM_G: O_UAV_02_LM_G
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_UAV_AI";
		typicalCargo[] = {"O_UAV_AI"};
		textureList[] = {"OFCRA_CC4_olive", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_olive.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { [_v, ['GMG_40mm']] spawn { params ['_v', '_rem']; sleep 1; if (!alive _v) exitWith {}; { private _w = _x; private _mags = compatibleMagazines _w; { private _t = _x; _v removeWeaponTurret [_w, _t]; { _v removeMagazinesTurret [_x, _t] } forEach _mags } forEach ([[-1]] + allTurrets [_v, false]) } forEach _rem; }; };";
			};
		};
	};
};
