// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 7: UK3CB_M1030 (OFCRA_CC4) - spawnable: UK3CB_AAF_B_M1030, UK3CB_AAF_I_M1030, UK3CB_AAF_O_M1030, UK3CB_ADA_B_M1030, UK3CB_ADA_I_M1030, UK3CB_ADA_O_M1030, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_motorbikes
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Motorbikes"
		};
	};
};

class CfgVehicles
{
	class UK3CB_TT650;

	class UK3CB_M1030: UK3CB_TT650
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\motorbikes\motorbikes_0.paa",
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_motorbikes\data\m1030_alfa_ca.paa"
				};
				factions[] = {};
			};
		};
	};
};
