// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for landrover - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_landrover_uk3cb_factions_adc_b
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_ADC_B_LR_Open",
			"OFCRA_CC4_O_UK3CB_ADC_O_LR_Open"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_landrover",
			"UK3CB_Factions_ADC_B",
			"UK3CB_Factions_ADC_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_C_LandRover_Open;
	class UK3CB_ADC_B_LR_Open: UK3CB_C_LandRover_Open
	{
		class EventHandlers;
	};
	class UK3CB_ADC_O_LR_Open: UK3CB_C_LandRover_Open
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_ADC_B_LR_Open: UK3CB_ADC_B_LR_Open
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\landrover\landrover_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_ADC_O_LR_Open: UK3CB_ADC_O_LR_Open
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\landrover\landrover_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_special_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_mg-spg9_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_landrover\data\ion_lr_glass_ca.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};
};
