// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for hmmwv - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_hmmwv
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_AAF_B_M1025_TOW",
			"OFCRA_CC4_O_UK3CB_KRG_O_M1025_TOW"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_hmmwv",
			"UK3CB_Factions_AAF_B",
			"UK3CB_Factions_KRG_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_B_M1025_TOW_AAF;
	class UK3CB_O_M1025_TOW_DES;
	class UK3CB_AAF_B_M1025_TOW: UK3CB_B_M1025_TOW_AAF
	{
		class EventHandlers;
		class Turrets;
	};
	class OFCRA_CC4_ti2_UK3CB_AAF_B_M1025_TOW: UK3CB_AAF_B_M1025_TOW
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class TOW_Turret;
		};
	};
	class OFCRA_CC4_ti3_UK3CB_AAF_B_M1025_TOW: OFCRA_CC4_ti2_UK3CB_AAF_B_M1025_TOW
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class TOW_Turret: TOW_Turret
			{
				class OpticsIn;
			};
		};
	};
	class OFCRA_CC4_ti4_UK3CB_AAF_B_M1025_TOW: OFCRA_CC4_ti3_UK3CB_AAF_B_M1025_TOW
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class TOW_Turret: TOW_Turret
			{
				class OpticsIn: OpticsIn
				{
					class Wide_TI;
					class Narrow_TI;
				};
			};
		};
	};
	class UK3CB_KRG_O_M1025_TOW: UK3CB_O_M1025_TOW_DES
	{
		class EventHandlers;
		class Turrets;
	};
	class OFCRA_CC4_ti2_UK3CB_KRG_O_M1025_TOW: UK3CB_KRG_O_M1025_TOW
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class TOW_Turret;
		};
	};
	class OFCRA_CC4_ti3_UK3CB_KRG_O_M1025_TOW: OFCRA_CC4_ti2_UK3CB_KRG_O_M1025_TOW
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class TOW_Turret: TOW_Turret
			{
				class OpticsIn;
			};
		};
	};
	class OFCRA_CC4_ti4_UK3CB_KRG_O_M1025_TOW: OFCRA_CC4_ti3_UK3CB_KRG_O_M1025_TOW
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class TOW_Turret: TOW_Turret
			{
				class OpticsIn: OpticsIn
				{
					class Wide_TI;
					class Narrow_TI;
				};
			};
		};
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_M1025_TOW: OFCRA_CC4_ti4_UK3CB_AAF_B_M1025_TOW
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_exterior_co.paa",
			"\rhsusf\addons\rhsusf_hmmwv\textures\m998_interior_d_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_a2_parts_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_wheel_wranglermt_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_mainbody_co.paa",
			"\rhsusf\addons\rhsusf_hmmwv\textures\gratting_w_co.paa",
			"\rhsusf\addons\rhsusf_hmmwv\textures\tile_exmetal_co.paa",
			"ofcra_cc4\hmmwv\hmmwv_7.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa",
			"",
			"",
			"",
			""
		};
		class Turrets: Turrets
		{
			class TOW_Turret: TOW_Turret
			{
				class OpticsIn: OpticsIn
				{
					class Wide_TI: Wide_TI
					{
						visionMode[] = {"Normal"};
						thermalMode[] = {};
					};
					class Narrow_TI: Narrow_TI
					{
						visionMode[] = {"Normal"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_KRG_O_M1025_TOW: OFCRA_CC4_ti4_UK3CB_KRG_O_M1025_TOW
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_exterior_co.paa",
			"\rhsusf\addons\rhsusf_hmmwv\textures\m998_interior_d_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_a2_parts_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_wheel_wranglermt_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled\uk3cb_factions_vehicles_hmmwv\data\ion_m998_mainbody_co.paa",
			"\rhsusf\addons\rhsusf_hmmwv\textures\gratting_w_co.paa",
			"\rhsusf\addons\rhsusf_hmmwv\textures\tile_exmetal_co.paa",
			"ofcra_cc4\hmmwv\hmmwv_7.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\uk3cb_factions_vehicles_common\decal\no_ca.paa",
			"",
			"",
			"",
			""
		};
		class Turrets: Turrets
		{
			class TOW_Turret: TOW_Turret
			{
				class OpticsIn: OpticsIn
				{
					class Wide_TI: Wide_TI
					{
						visionMode[] = {"Normal"};
						thermalMode[] = {};
					};
					class Narrow_TI: Narrow_TI
					{
						visionMode[] = {"Normal"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};
};
