// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 54: mkk_warrior_base (OFCRA_CC4) - spawnable: mkk_warrior_b
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_warrior
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"warrior_c"
		};
	};
};

class CfgVehicles
{
	class Tank_F;

	class mkk_warrior_base: Tank_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\warrior\warrior_0.paa",
					"ofcra_cc4\warrior\warrior_1.paa",
					"ofcra_cc4\warrior\warrior_2.paa",
					"ofcra_cc4\warrior\warrior_3.paa",
					"ofcra_cc4\warrior\warrior_4.paa",
					"",
					"",
					"",
					""
				};
				factions[] = {};
			};
		};
	};
};
