// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for m109 - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_m109
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_OFCRA_m109tank",
			"OFCRA_CC4_O_OFCRA_m109tank"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_m109",
			"ofcra_rhs_usf_m109"
		};
	};
};

class CfgVehicles
{
	class rhsusf_m109_usarmy;
	class OFCRA_m109tank: rhsusf_m109_usarmy
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_OFCRA_m109tank: OFCRA_m109tank
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\m109\m109_0.paa",
			"ofcra_cc4\m109\m109_1.paa",
			"ofcra_cc4\m109\m109_2.paa",
			"\rhsusf\addons\rhsusf_m109\data\rhsusf_m109a6_mesh_d_ca.paa",
			"ofcra_cc4\m109\m109_4.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_OFCRA_m109tank: OFCRA_m109tank
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\m109\m109_0.paa",
			"ofcra_cc4\m109\m109_1.paa",
			"ofcra_cc4\m109\m109_2.paa",
			"\rhsusf\addons\rhsusf_m109\data\rhsusf_m109a6_mesh_d_ca.paa",
			"ofcra_cc4\m109\m109_4.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
