// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for cv9030 - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_cv9030
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_mkk_cv9030",
			"OFCRA_CC4_O_mkk_cv_9030_r"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_cv9030",
			"mkk_cv_9030"
		};
	};
};

class CfgVehicles
{
	class cv_9030_base_Tank_F;
	class mkk_cv9030: cv_9030_base_Tank_F
	{
		class EventHandlers;
	};
	class mkk_cv_9030_r: mkk_cv9030
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_mkk_cv9030: mkk_cv9030
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\cv9030\cv9030_0.paa",
			"ofcra_cc4\cv9030\cv9030_1.paa",
			"ofcra_cc4\cv9030\cv9030_2.paa",
			"ofcra_cc4\cv9030\cv9030_3.paa",
			"\bmp_2m\data\rifled_barrel_b_co.paa",
			"\t_64_b_bv\data\mg_pkt_co.paa",
			"\cv_9030\data\strf_90c_track_co.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_mkk_cv_9030_r: mkk_cv_9030_r
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\cv9030\cv9030_0.paa",
			"ofcra_cc4\cv9030\cv9030_1.paa",
			"ofcra_cc4\cv9030\cv9030_2.paa",
			"ofcra_cc4\cv9030\cv9030_3.paa",
			"\bmp_2m\data\rifled_barrel_b_co.paa",
			"\t_64_b_bv\data\mg_pkt_co.paa",
			"\cv_9030\data\strf_90c_track_co.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
