// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 44: UAV_03_base_F (OFCRA_CC4) - spawnable: B_T_UAV_03_dynamicLoadout_F
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_uav03_falcon
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"A3_Air_F_Exp_UAV_03"
		};
	};
};

class CfgVehicles
{
	class Helicopter_Base_F;

	class UAV_03_base_F: Helicopter_Base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav03_falcon\uav03_falcon_0.paa",
					"ofcra_cc4\uav03_falcon\uav03_falcon_1.paa",
					"ofcra_cc4\uav03_falcon\uav03_falcon_2.paa"
				};
				factions[] = {};
			};
		};
	};
};
