// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for dingo - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_dingo
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_AAF_B_Dingo",
			"OFCRA_CC4_O_UK3CB_LDF_O_Dingo"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_dingo",
			"UK3CB_Factions_AAF_B",
			"UK3CB_Factions_LDF_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_B_Dingo_AAF;
	class UK3CB_O_Dingo_LDF;
	class UK3CB_AAF_B_Dingo: UK3CB_B_Dingo_AAF
	{
		class EventHandlers;
	};
	class UK3CB_LDF_O_Dingo: UK3CB_O_Dingo_LDF
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_Dingo: UK3CB_AAF_B_Dingo
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\dingo\dingo_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\a_teile_ion_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\innen_teile2_co.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_LDF_O_Dingo: UK3CB_LDF_O_Dingo
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\dingo\dingo_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\a_teile_ion_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\wheeled2\uk3cb_factions_vehicles_dingo\data\innen_teile2_co.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
