// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 40: MMM_UAV_Vampire (OFCRA_CC4) - spawnable: MMM_UAV_Vampire
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_babayaga
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"MMM_UA_BabaYaga"
		};
	};
};

class CfgVehicles
{
	class UAV_06_base_F;

	class MMM_UAV_Vampire: UAV_06_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\babayaga\babayaga_0.paa",
					"ofcra_cc4\babayaga\babayaga_1.paa"
				};
				factions[] = {};
			};
		};
	};
};
