// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for boxer - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_boxer
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_mkk_boxer_ifv_b",
			"OFCRA_CC4_O_mkk_boxer_ifv_r",
			"OFCRA_CC4_B_mkk_boxer_mgs_b",
			"OFCRA_CC4_O_mkk_boxer_mgs_r",
			"OFCRA_CC4_B_mkk_boxer_ranger_b",
			"OFCRA_CC4_O_mkk_boxer_ranger_r"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_boxer",
			"boxer_c"
		};
	};
};

class CfgVehicles
{
	class mkk_boxer_ifv_base;
	class mkk_boxer_mgs_base;
	class mkk_boxer_ranger_base;
	class mkk_boxer_ifv_b: mkk_boxer_ifv_base
	{
		class EventHandlers;
	};
	class mkk_boxer_ifv_r: mkk_boxer_ifv_base
	{
		class EventHandlers;
	};
	class mkk_boxer_mgs_b: mkk_boxer_mgs_base
	{
		class EventHandlers;
	};
	class mkk_boxer_mgs_r: mkk_boxer_mgs_base
	{
		class EventHandlers;
	};
	class mkk_boxer_ranger_b: mkk_boxer_ranger_base
	{
		class EventHandlers;
	};
	class mkk_boxer_ranger_r: mkk_boxer_ranger_base
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_mkk_boxer_ifv_b: mkk_boxer_ifv_b
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\boxer\boxer_0.paa",
			"ofcra_cc4\boxer\boxer_1.paa",
			"ofcra_cc4\boxer\boxer_2.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_mkk_boxer_ifv_r: mkk_boxer_ifv_r
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\boxer\boxer_0.paa",
			"ofcra_cc4\boxer\boxer_1.paa",
			"ofcra_cc4\boxer\boxer_2.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_B_mkk_boxer_mgs_b: mkk_boxer_mgs_b
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\boxer\boxer_0.paa",
			"ofcra_cc4\boxer\boxer_1.paa",
			"ofcra_cc4\boxer\boxer_2.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_mkk_boxer_mgs_r: mkk_boxer_mgs_r
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\boxer\boxer_0.paa",
			"ofcra_cc4\boxer\boxer_1.paa",
			"ofcra_cc4\boxer\boxer_2.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_B_mkk_boxer_ranger_b: mkk_boxer_ranger_b
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\boxer\boxer_0.paa",
			"ofcra_cc4\boxer\boxer_1.paa",
			"ofcra_cc4\boxer\boxer_2.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_mkk_boxer_ranger_r: mkk_boxer_ranger_r
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\boxer\boxer_0.paa",
			"ofcra_cc4\boxer\boxer_1.paa",
			"ofcra_cc4\boxer\boxer_2.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
