// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for caiman - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_caiman
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_rhsusf_M1220_M2_usarmy_d",
			"OFCRA_CC4_O_rhsusf_M1220_M2_usarmy_d"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_caiman",
			"rhsusf_c_Caiman"
		};
	};
};

class CfgVehicles
{
	class rhsusf_caiman_GPK_base;
	class rhsusf_M1220_M2_usarmy_d: rhsusf_caiman_GPK_base
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_rhsusf_M1220_M2_usarmy_d: rhsusf_M1220_M2_usarmy_d
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\caiman\caiman_0.paa",
			"ofcra_cc4\caiman\caiman_1.paa",
			"ofcra_cc4\caiman\caiman_2.paa",
			"ofcra_cc4\caiman\caiman_3.paa",
			"ofcra_cc4\caiman\caiman_4.paa",
			"ofcra_cc4\caiman\caiman_5.paa",
			"ofcra_cc4\caiman\caiman_6.paa",
			"ofcra_cc4\caiman\caiman_7.paa",
			"ofcra_cc4\caiman\caiman_8.paa",
			"ofcra_cc4\caiman\caiman_9.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_rhsusf_M1220_M2_usarmy_d: rhsusf_M1220_M2_usarmy_d
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\caiman\caiman_0.paa",
			"ofcra_cc4\caiman\caiman_1.paa",
			"ofcra_cc4\caiman\caiman_2.paa",
			"ofcra_cc4\caiman\caiman_3.paa",
			"ofcra_cc4\caiman\caiman_4.paa",
			"ofcra_cc4\caiman\caiman_5.paa",
			"ofcra_cc4\caiman\caiman_6.paa",
			"ofcra_cc4\caiman\caiman_7.paa",
			"ofcra_cc4\caiman\caiman_8.paa",
			"ofcra_cc4\caiman\caiman_9.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
