// Generated by Build-CC4Faction.ps1
// Hidden CC4 bases with the thermals removed in the config and the CC4 init event handler,
// for CC4 classes that aren't generated (the VBIED): class OFCRA_B_UGV_01_VBIED_F: OFCRA_CC4_NoTI_B_UGV_01_F

class CfgPatches
{
	class ofcra_cc4_faction_nothermal
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"A3_Drones_F_Soft_F_Gamma_UGV_01"
		};
	};
};

class CfgVehicles
{
	class UGV_01_base_F;
	class B_UGV_01_F: UGV_01_base_F
	{
		class EventHandlers;
	};
	class OFCRA_CC4_NoTI_B_UGV_01_F: B_UGV_01_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};
	class O_UGV_01_F: UGV_01_base_F
	{
		class EventHandlers;
	};
	class OFCRA_CC4_NoTI_O_UGV_01_F: O_UGV_01_F
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};
};
