// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// caiman is split by required addons (2 configs) so a missing mod only skips its own part
// vehicles.txt line 25: UK3CB_Caiman_Police_Base (OFCRA_CC4) - spawnable: UK3CB_APD_B_Caiman_Police, UK3CB_APD_I_Caiman_Police, UK3CB_TPD_B_Caiman_Police, UK3CB_TPD_I_Caiman_Police, UK3CB_TPD_O_Caiman_Police
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_caiman_uk3cb_factions_vehicles_caiman
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Caiman"
		};
	};
};

class CfgVehicles
{
	class rhsusf_caiman_base;

	class UK3CB_Caiman_Police_Base: rhsusf_caiman_base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\caiman\caiman_0.paa",
					"ofcra_cc4\caiman\caiman_1.paa",
					"ofcra_cc4\caiman\caiman_2.paa",
					"ofcra_cc4\caiman\caiman_3.paa",
					"ofcra_cc4\caiman\caiman_4.paa",
					"ofcra_cc4\caiman\caiman_5.paa",
					"ofcra_cc4\caiman\caiman_6.paa",
					"ofcra_cc4\caiman\caiman_7.paa",
					"ofcra_cc4\caiman\caiman_8.paa",
					"ofcra_cc4\caiman\caiman_9.paa"
				};
				factions[] = {};
			};
		};
	};
};
