// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for m113 - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_m113
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_ANA_B_M113_M2",
			"OFCRA_CC4_O_UK3CB_FIA_O_M113_M2"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_m113",
			"UK3CB_Factions_ANA_B",
			"UK3CB_Factions_FIA_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_B_M113tank_M2_ANA;
	class UK3CB_O_M113tank_M2_FIA;
	class UK3CB_ANA_B_M113_M2: UK3CB_B_M113tank_M2_ANA
	{
		class EventHandlers;
		class AnimationSources;
	};
	class UK3CB_FIA_O_M113_M2: UK3CB_O_M113tank_M2_FIA
	{
		class EventHandlers;
		class AnimationSources;
	};

	class OFCRA_CC4_B_UK3CB_ANA_B_M113_M2: UK3CB_ANA_B_M113_M2
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_crew_F";
		typicalCargo[] = {"B_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\m113\m113_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_02_h_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_03_co.paa",
			"\rhsusf\addons\rhsusf_m113\data_new\m113a3_int03_d_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m23_pintle_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_shield_co.paa"
		};
		animationList[] = {};
		class AnimationSources: AnimationSources
		{
			class Hide_Turret_Armor_Front
			{
				source = "user";
				animPeriod = 0.00001;
				initPhase = 1;
				displayName = "Hide Turret Armor Front";
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_FIA_O_M113_M2: UK3CB_FIA_O_M113_M2
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_crew_F";
		typicalCargo[] = {"O_crew_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\m113\m113_0.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_02_h_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_03_co.paa",
			"\rhsusf\addons\rhsusf_m113\data_new\m113a3_int03_d_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m23_pintle_co.paa",
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\apc\uk3cb_factions_vehicles_m113\data\ion_b_m113a3_shield_co.paa"
		};
		animationList[] = {};
		class AnimationSources: AnimationSources
		{
			class Hide_Turret_Armor_Front
			{
				source = "user";
				animPeriod = 0.00001;
				initPhase = 1;
				displayName = "Hide Turret Armor Front";
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
