// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// uav02_greyhawk is split by required addons (4 configs) so a missing mod only skips its own part
// vehicles.txt line 46: UK3CB_Ababil_Base (OFCRA_CC4) - spawnable: UK3CB_CSAT_A_O_Ababil_AT, UK3CB_CSAT_A_O_Ababil_CAS, UK3CB_CSAT_B_O_Ababil_AT, UK3CB_CSAT_B_O_Ababil_CAS, UK3CB_CSAT_F_O_Ababil_AT, UK3CB_CSAT_F_O_Ababil_CAS, ...
// vehicles.txt line 46: UK3CB_Ababil_Base (OFCRA_CC4_db) - spawnable: UK3CB_CSAT_A_O_Ababil_AT, UK3CB_CSAT_A_O_Ababil_CAS, UK3CB_CSAT_B_O_Ababil_AT, UK3CB_CSAT_B_O_Ababil_CAS, UK3CB_CSAT_F_O_Ababil_AT, UK3CB_CSAT_F_O_Ababil_CAS, ...
// vehicles.txt line 46: UK3CB_Ababil_Base (OFCRA_CC4_olive) - spawnable: UK3CB_CSAT_A_O_Ababil_AT, UK3CB_CSAT_A_O_Ababil_CAS, UK3CB_CSAT_B_O_Ababil_AT, UK3CB_CSAT_B_O_Ababil_CAS, UK3CB_CSAT_F_O_Ababil_AT, UK3CB_CSAT_F_O_Ababil_CAS, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_db", 1]] call BIS_fnc_initVehicle;
// In a mission:  [_veh, ["OFCRA_CC4_olive", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_uav02_greyhawk_uk3cb_factions_vehicles_ababil
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Ababil"
		};
	};
};

class CfgVehicles
{
	class UAV_02_CAS_base_F;

	class UK3CB_Ababil_Base: UAV_02_CAS_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_db
			{
				displayName = "OFCRA CC4 Dark Brown";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_db.paa"
				};
				factions[] = {};
			};
			class OFCRA_CC4_olive
			{
				displayName = "OFCRA CC4 Olive";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_olive.paa"
				};
				factions[] = {};
			};
		};
	};
};
