// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for huey - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_huey
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_AAF_B_UH1H",
			"OFCRA_CC4_O_UK3CB_AAF_O_UH1H",
			"OFCRA_CC4_B_UK3CB_AAF_B_UH1H_GUNSHIP",
			"OFCRA_CC4_O_UK3CB_AAF_O_UH1H_GUNSHIP",
			"OFCRA_CC4_B_UK3CB_AAF_B_UH1H_M240",
			"OFCRA_CC4_O_UK3CB_AAF_O_UH1H_M240"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_huey",
			"UK3CB_Factions_AAF_B",
			"UK3CB_Factions_AAF_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_B_UH1H_M240_AAF;
	class UK3CB_O_UH1H_M240_AAF;
	class UK3CB_B_UH1H_AAF;
	class UK3CB_B_UH1H_GUNSHIP_AAF;
	class UK3CB_O_UH1H_AAF;
	class UK3CB_O_UH1H_GUNSHIP_AAF;
	class UK3CB_AAF_B_UH1H_M240: UK3CB_B_UH1H_M240_AAF
	{
		class EventHandlers;
	};
	class UK3CB_AAF_O_UH1H_M240: UK3CB_O_UH1H_M240_AAF
	{
		class EventHandlers;
	};
	class UK3CB_AAF_B_UH1H: UK3CB_B_UH1H_AAF
	{
		class EventHandlers;
	};
	class UK3CB_AAF_B_UH1H_GUNSHIP: UK3CB_B_UH1H_GUNSHIP_AAF
	{
		class EventHandlers;
	};
	class UK3CB_AAF_O_UH1H: UK3CB_O_UH1H_AAF
	{
		class EventHandlers;
	};
	class UK3CB_AAF_O_UH1H_GUNSHIP: UK3CB_O_UH1H_GUNSHIP_AAF
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_UH1H: UK3CB_AAF_B_UH1H
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Helipilot_F";
		typicalCargo[] = {"B_Helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_AAF_O_UH1H: UK3CB_AAF_O_UH1H
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_helipilot_F";
		typicalCargo[] = {"O_helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_UH1H_GUNSHIP: UK3CB_AAF_B_UH1H_GUNSHIP
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Helipilot_F";
		typicalCargo[] = {"B_Helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_AAF_O_UH1H_GUNSHIP: UK3CB_AAF_O_UH1H_GUNSHIP
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_helipilot_F";
		typicalCargo[] = {"O_helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_B_UK3CB_AAF_B_UH1H_M240: UK3CB_AAF_B_UH1H_M240
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Helipilot_F";
		typicalCargo[] = {"B_Helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_AAF_O_UH1H_M240: UK3CB_AAF_O_UH1H_M240
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_helipilot_F";
		typicalCargo[] = {"O_helipilot_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
			"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
