// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for mrzr - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_mrzr
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_rhsusf_mrzr4_d",
			"OFCRA_CC4_O_rhsusf_mrzr4_d"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_mrzr",
			"rhsusf_c_mrzr"
		};
	};
};

class CfgVehicles
{
	class rhsusf_mrzr_base;
	class rhsusf_mrzr4_d: rhsusf_mrzr_base
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_rhsusf_mrzr4_d: rhsusf_mrzr4_d
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\mrzr\mrzr_0.paa",
			"ofcra_cc4\mrzr\mrzr_1.paa",
			"ofcra_cc4\mrzr\mrzr_2.paa",
			"ofcra_cc4\mrzr\mrzr_3.paa",
			"ofcra_cc4\mrzr\mrzr_4.paa",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_rhsusf_mrzr4_d: rhsusf_mrzr4_d
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\mrzr\mrzr_0.paa",
			"ofcra_cc4\mrzr\mrzr_1.paa",
			"ofcra_cc4\mrzr\mrzr_2.paa",
			"ofcra_cc4\mrzr\mrzr_3.paa",
			"ofcra_cc4\mrzr\mrzr_4.paa",
			"",
			"",
			"",
			"",
			"",
			"",
			""
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
