// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for transit - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_transit
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_WEI_B_Transit_Transport",
			"OFCRA_CC4_O_UK3CB_WEI_O_Transit_Transport"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_transit",
			"UK3CB_Factions_WEI_B",
			"UK3CB_Factions_WEI_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_C_Van_Transit_Transport;
	class UK3CB_WEI_B_Transit_Transport: UK3CB_C_Van_Transit_Transport
	{
		class EventHandlers;
	};
	class UK3CB_WEI_O_Transit_Transport: UK3CB_C_Van_Transit_Transport
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_WEI_B_Transit_Transport: UK3CB_WEI_B_Transit_Transport
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_Soldier_F";
		typicalCargo[] = {"B_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\transit\transit_0.paa",
			"\a3\soft_f_orange\van_02\data\van_wheel_transport_co.paa",
			"\a3\soft_f_orange\van_02\data\van_glass_transport_ca.paa",
			"ofcra_cc4\transit\transit_0.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_WEI_O_Transit_Transport: UK3CB_WEI_O_Transit_Transport
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_Soldier_F";
		typicalCargo[] = {"O_Soldier_F"};
		textureList[] = {"OFCRA_CC4", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\transit\transit_0.paa",
			"\a3\soft_f_orange\van_02\data\van_wheel_transport_co.paa",
			"\a3\soft_f_orange\van_02\data\van_glass_transport_ca.paa",
			"ofcra_cc4\transit\transit_0.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
