// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 36: rhsusf_m109tank_base (OFCRA_CC4) - spawnable: OFCRA_m109tank, OFCRA_m109tank_d, rhsusf_m109d_usarmy, rhsusf_m109_usarmy, UK3CB_AAF_B_M109, UK3CB_CW_US_B_EARLY_M109, ...
// vehicles.txt line 36: UK3CB_M109_Base (OFCRA_CC4) - spawnable: UK3CB_AAF_B_M109, UK3CB_CW_US_B_EARLY_M109, UK3CB_CW_US_B_LATE_M109, UK3CB_KRG_B_M109, UK3CB_KRG_I_M109, UK3CB_KRG_O_M109
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_m109
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"rhsusf_c_m109",
			"UK3CB_Factions_Vehicles_M109"
		};
	};
};

class CfgVehicles
{
	class MBT_01_arty_base_F;

	class rhsusf_m109tank_base: MBT_01_arty_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\m109\m109_0.paa",
					"ofcra_cc4\m109\m109_1.paa",
					"ofcra_cc4\m109\m109_2.paa",
					"\rhsusf\addons\rhsusf_m109\data\rhsusf_m109a6_mesh_d_ca.paa",
					"ofcra_cc4\m109\m109_4.paa"
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_M109_Base: rhsusf_m109tank_base
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\m109\m109_0.paa",
					"ofcra_cc4\m109\m109_1.paa",
					"ofcra_cc4\m109\m109_2.paa",
					"\rhsusf\addons\rhsusf_m109\data\rhsusf_m109a6_mesh_d_ca.paa",
					"ofcra_cc4\m109\m109_4.paa"
				};
				factions[] = {};
			};
		};
	};
};
