// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for ugv01_stomper - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_ugv01_stomper
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_CSAT_A_O_UGV_Armed",
			"OFCRA_CC4_O_UK3CB_CSAT_A_O_UGV_Armed"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_ugv01_stomper_uk3cb_factions_vehicles_stomper",
			"UK3CB_Factions_CSAT_A_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_O_UGV_Armed_CSAT_A;
	class UK3CB_CSAT_A_O_UGV_Armed: UK3CB_O_UGV_Armed_CSAT_A
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_CSAT_A_O_UGV_Armed: UK3CB_CSAT_A_O_UGV_Armed
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_UAV_AI";
		typicalCargo[] = {"B_UAV_AI"};
		textureList[] = {"OFCRA_CC4_db", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_db.paa",
			"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_db.paa",
			"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_db.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_CSAT_A_O_UGV_Armed: UK3CB_CSAT_A_O_UGV_Armed
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_UAV_AI";
		typicalCargo[] = {"O_UAV_AI"};
		textureList[] = {"OFCRA_CC4_olive", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\ugv01_stomper\ugv01_stomper_0_olive.paa",
			"ofcra_cc4\ugv01_stomper\ugv01_stomper_1_olive.paa",
			"ofcra_cc4\ugv01_stomper\ugv01_stomper_2_olive.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
