// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 11: UK3CB_Van_Transit_Transport_Base (OFCRA_CC4) - spawnable: UK3CB_APD_B_Transit_Transport, UK3CB_APD_I_Transit_Transport, UK3CB_APD_O_Transit_Transport, UK3CB_ION_B_Desert_Transit_Transport, UK3CB_ION_B_Urban_Transit_Transport, UK3CB_ION_B_Winter_Transit_Transport, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_transit
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_Transit"
		};
	};
};

class CfgVehicles
{
	class Van_02_transport_base_F;

	class UK3CB_Van_Transit_Transport_Base: Van_02_transport_base_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\transit\transit_0.paa",
					"\a3\soft_f_orange\van_02\data\van_wheel_transport_co.paa",
					"\a3\soft_f_orange\van_02\data\van_glass_transport_ca.paa",
					"ofcra_cc4\transit\transit_0.paa"
				};
				factions[] = {};
			};
		};
	};
};
