// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for uav02_greyhawk - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_uav02_greyhawk_uk3cb_factions_tka_o
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_TKA_U_O_Shahed",
			"OFCRA_CC4_O_UK3CB_TKA_U_O_Shahed"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_uav02_greyhawk_uk3cb_factions_vehicles_shahed",
			"UK3CB_Factions_TKA_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_O_Shahed_TKA;
	class UK3CB_TKA_U_O_Shahed: UK3CB_O_Shahed_TKA
	{
		class EventHandlers;
	};

	class OFCRA_CC4_B_UK3CB_TKA_U_O_Shahed: UK3CB_TKA_U_O_Shahed
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_UAV_AI";
		typicalCargo[] = {"B_UAV_AI"};
		textureList[] = {"OFCRA_CC4_db", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_db.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_TKA_U_O_Shahed: UK3CB_TKA_U_O_Shahed
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_UAV_AI";
		typicalCargo[] = {"O_UAV_AI"};
		textureList[] = {"OFCRA_CC4_olive", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_olive.paa"
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true;";
			};
		};
	};
};
