// Generated by Build-CC4Faction.ps1
// CC4 faction vehicles for uav02_greyhawk - blue copies in OFCRA_CC4_B, red copies in OFCRA_CC4_O

class CfgPatches
{
	class ofcra_cc4_faction_uav02_greyhawk_uk3cb_factions_tka_o
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] =
		{
			"OFCRA_CC4_B_UK3CB_TKA_U_O_Shahed",
			"OFCRA_CC4_O_UK3CB_TKA_U_O_Shahed"
		};
		weapons[] = {};
		requiredAddons[] =
		{
			"ofcra_cc4_faction",
			"ofcra_cc4_uav02_greyhawk_uk3cb_factions_vehicles_shahed",
			"UK3CB_Factions_TKA_O"
		};
	};
};

class CfgVehicles
{
	class UK3CB_O_Shahed_TKA;
	class UK3CB_TKA_U_O_Shahed: UK3CB_O_Shahed_TKA
	{
		class EventHandlers;
		class Turrets;
	};
	class OFCRA_CC4_ti2_UK3CB_TKA_U_O_Shahed: UK3CB_TKA_U_O_Shahed
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret;
		};
	};
	class OFCRA_CC4_ti3_UK3CB_TKA_U_O_Shahed: OFCRA_CC4_ti2_UK3CB_TKA_U_O_Shahed
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn;
			};
		};
	};
	class OFCRA_CC4_ti4_UK3CB_TKA_U_O_Shahed: OFCRA_CC4_ti3_UK3CB_TKA_U_O_Shahed
	{
		scope = 0;
		scopeCurator = 0;
		class EventHandlers: EventHandlers
		{
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide;
					class Medium;
					class Narrow;
				};
			};
		};
	};

	class OFCRA_CC4_B_UK3CB_TKA_U_O_Shahed: OFCRA_CC4_ti4_UK3CB_TKA_U_O_Shahed
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 1;
		faction = "OFCRA_CC4_B";
		crew = "B_UAV_AI";
		typicalCargo[] = {"B_UAV_AI"};
		textureList[] = {"OFCRA_CC4_db", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_db.paa"
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};

	class OFCRA_CC4_O_UK3CB_TKA_U_O_Shahed: OFCRA_CC4_ti4_UK3CB_TKA_U_O_Shahed
	{
		author = "OFCRA Wombat";
		scope = 2;
		scopeCurator = 2;
		side = 0;
		faction = "OFCRA_CC4_O";
		crew = "O_UAV_AI";
		typicalCargo[] = {"O_UAV_AI"};
		textureList[] = {"OFCRA_CC4_olive", 1};
		hiddenSelectionsTextures[] =
		{
			"ofcra_cc4\uav02_greyhawk\uav02_greyhawk_0_olive.paa"
		};
		class Turrets: Turrets
		{
			class MainTurret: MainTurret
			{
				class OpticsIn: OpticsIn
				{
					class Wide: Wide
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Medium: Medium
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
					class Narrow: Narrow
					{
						visionMode[] = {"Normal", "NVG"};
						thermalMode[] = {};
					};
				};
			};
		};
		class EventHandlers: EventHandlers
		{
			class ofcra_cc4
			{
				init = "params ['_v']; _v setVariable ['tf_hasRadio', false, false]; _v disableTIEquipment true; if (!is3DEN) then { _v spawn { sleep 1; _this disableTIEquipment true; sleep 5; _this disableTIEquipment true; }; };";
			};
		};
	};
};
