// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 52: UK3CB_M60a3 (OFCRA_CC4) - spawnable: UK3CB_AAF_B_M60A3, UK3CB_AAF_I_M60A1, UK3CB_AAF_I_M60A3, UK3CB_B_M60A1_HIDF, UK3CB_B_M60A3_HIDF, UK3CB_CW_US_B_EARLY_M60a1, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_m60
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_M60"
		};
	};
};

class CfgVehicles
{
	class Tank_F;

	class UK3CB_M60a3: Tank_F
	{
		class TextureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"ofcra_cc4\m60\m60_0.paa",
					"ofcra_cc4\m60\m60_1.paa",
					"ofcra_cc4\m60\m60_2.paa",
					"ofcra_cc4\m60\m60_3.paa",
					"ofcra_cc4\m60\m60_4.paa"
				};
				factions[] = {};
			};
		};
	};
};
