// Generated by Build-ModConfigs.ps1 from C:\Users\aridd\Desktop\arma3-textures\cc4\vehicles.txt
// vehicles.txt line 50: UK3CB_UH1H (OFCRA_CC4) - spawnable: UK3CB_AAF_B_UH1H, UK3CB_AAF_I_UH1H, UK3CB_AAF_O_UH1H, UK3CB_ADA_B_UH1H, UK3CB_ADA_I_UH1H, UK3CB_ADA_O_UH1H, ...
// vehicles.txt line 50: UK3CB_UH1H_GUNSHIP (OFCRA_CC4) - spawnable: UK3CB_AAF_B_UH1H_GUNSHIP, UK3CB_AAF_I_UH1H_GUNSHIP, UK3CB_AAF_O_UH1H_GUNSHIP, UK3CB_ADA_B_UH1H_GUNSHIP, UK3CB_ADA_I_UH1H_GUNSHIP, UK3CB_ADA_O_UH1H_GUNSHIP, ...
// vehicles.txt line 50: UK3CB_UH1H_M240 (OFCRA_CC4) - spawnable: UK3CB_AAF_B_UH1H_M240, UK3CB_AAF_I_UH1H_M240, UK3CB_AAF_O_UH1H_M240, UK3CB_ADA_B_UH1H_M240, UK3CB_ADA_I_UH1H_M240, UK3CB_ADA_O_UH1H_M240, ...
// In a mission:  [_veh, ["OFCRA_CC4", 1]] call BIS_fnc_initVehicle;

class CfgPatches
{
	class ofcra_cc4_huey
	{
		author = "OFCRA Wombat";
		skipWhenMissingDependencies = 1;
		units[] = {};
		weapons[] = {};
		requiredAddons[] =
		{
			"UK3CB_Factions_Vehicles_UH1H"
		};
	};
};

class CfgVehicles
{
	class rhs_uh1h_base;
	class rhs_uh1h_hidf: rhs_uh1h_base
	{
		class TextureSources;
	};
	class rhs_uh1h_hidf_gunship: rhs_uh1h_hidf
	{
		class TextureSources;
	};
	class rhs_uh1h_hidf_unarmed: rhs_uh1h_hidf
	{
		class TextureSources;
	};

	class UK3CB_UH1H_M240: rhs_uh1h_hidf
	{
		class TextureSources: textureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
					"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
					"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_UH1H: rhs_uh1h_hidf_unarmed
	{
		class TextureSources: textureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
					"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
					"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
					""
				};
				factions[] = {};
			};
		};
	};

	class UK3CB_UH1H_GUNSHIP: rhs_uh1h_hidf_gunship
	{
		class TextureSources: textureSources
		{
			class OFCRA_CC4
			{
				displayName = "OFCRA CC4";
				author = "OFCRA Wombat";
				textures[] =
				{
					"\uk3cb_factions\addons\uk3cb_factions_vehicles\air\uk3cb_factions_vehicles_uh1h\data\ion_b_uh1h_co.paa",
					"\rhsgref\addons\rhsgref_air\uh1h\data\uh1h_black_in_co.paa",
					"\rhsgref\addons\rhsgref_air\uh1h\data\mlod_black_co.paa",
					""
				};
				factions[] = {};
			};
		};
	};
};
